### Actualizacion de la base de datos

In [1]:
import pandas as pd
import mysql.connector

import numpy as np

Una vez ejecutados los script de scrapeo y procesamiento, pasamos a actualizar la base de datos

Conectamos con la base de datos

In [6]:
conn = mysql.connector.connect(
    host="localhost", 
    user="root", 
    password="contraseña",
    database="pisos3"
)

In [7]:
cursor = conn.cursor()

Cargamos los csv

In [2]:
df_sale = pd.read_csv("../data/processed/madrid_sale_properties_processed.csv")

In [3]:
df_sale

,url,property_id,price_eur,barrio,distrito,latitude,longitude,scraped_at,description,energy_cert_classification,...,superficie_construida,superficie_util,terraza,trastero,vidrios_dobles,energy_consumption_kwh_m2_yr,energy_emissions_kg_co2_m2_yr,gastos_comunidad_eur,orientacion_list,planta_numerica
0,https://www.pisos.com/comprar/piso-penagrande2...,5.423291e+10,590000.0,Peñagrande,Fuencarral-El Pardo,40.472631,-3.718548,2025-06-16T19:08:58.558695,31Real Servicios Inmobiliarios te ofrece la vi...,Pendiente de completar,...,125.0,NaN,True,True,False,NaN,NaN,100.0,['NE'],2.0
1,https://www.pisos.com/comprar/piso-valdezarza2...,5.505312e+10,390000.0,Valdezarza,Moncloa-Aravaca,40.465167,-3.710664,2025-06-16T19:09:00.479307,31REAL SERVICIOS INMOBILIARIOS VENDE: Precioso...,Pendiente de completar,...,76.0,70.0,True,False,False,NaN,NaN,NaN,['S'],3.0
2,https://www.pisos.com/comprar/piso-adelfas2800...,5.500244e+10,1075000.0,Adelfas,Retiro,40.405989,-3.669410,2025-06-16T19:09:02.425509,31Real Servicios Inmobiliarios ofrece en venta...,Pendiente de completar,...,132.0,NaN,False,True,False,NaN,NaN,100.0,['SO'],5.0
3,https://www.pisos.com/comprar/piso-pinar_del_r...,5.426156e+10,399000.0,Pinar del Rey,Hortaleza,40.475663,-3.649628,2025-06-16T19:09:04.273818,"Luz, espacio y una reforma impecable en un pis...",En trámite,...,79.0,76.0,True,False,True,NaN,NaN,60.0,NaN,1.0
4,https://www.pisos.com/comprar/piso-lista_barri...,5.343085e+10,455000.0,Lista,Salamanca,40.431876,-3.673652,2025-06-16T19:09:06.075324,Te presentamos este encantador piso con GARAJE...,En trámite,...,47.0,41.0,False,False,False,NaN,NaN,NaN,NaN,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2975,https://www.pisos.com/comprar/piso-pilar28029-...,5.339863e+10,290000.0,Pilar,Fuencarral-El Pardo,40.478543,-3.705271,2025-06-16T20:41:52.935318,Nmobiliaria tecnocasa barrio del pilar-la vagu...,Disponible,...,61.0,NaN,True,False,False,246.0,51.0,NaN,NaN,NaN
2976,https://www.pisos.com/comprar/piso-goya28009-5...,5.084455e+10,1300000.0,Goya,Salamanca,40.424744,-3.670807,2025-06-16T20:41:54.731735,*Las imágenes de las estancias amuebladas y de...,En trámite,...,137.0,NaN,False,False,False,NaN,NaN,100.0,['E'],1.0
2977,https://www.pisos.com/comprar/apartamento-goya...,4.756165e+10,1800000.0,Goya,Salamanca,40.421674,-3.674780,2025-06-16T20:41:56.595975,"Engel & Völkers, inmobiliaria de lujo, tiene e...",No indicado,...,191.0,NaN,False,False,False,NaN,NaN,NaN,NaN,NaN
2978,https://www.pisos.com/comprar/atico-universida...,4.587160e+10,1080000.0,Universidad-Malasaña,Centro,40.425055,-3.702991,2025-06-16T20:41:58.381915,Fortuny Real Estate ofrece ático de lujo a est...,En trámite,...,150.0,NaN,True,False,False,NaN,NaN,NaN,['E'],4.0
2979,https://www.pisos.com/comprar/apartamento-reco...,5.418658e+10,2309000.0,Recoletos,Salamanca,40.425238,-3.680946,2025-06-16T20:42:00.278871,Engel & Völkers tiene el placer de presentar e...,No indicado,...,132.0,NaN,False,False,False,NaN,NaN,NaN,NaN,2.0

In [4]:

df_rental = pd.read_csv("../data/processed/madrid_rental_properties_processed.csv")

In [5]:
df_rental

,url,property_id,barrio,distrito,latitude,longitude,scraped_at,description,energy_cert_classification,energy_consumption_rating,...,terraza,trastero,vidrios_dobles,price_eur_pm,energy_consumption_kwh_m2_yr,energy_emissions_kg_co2_m2_yr,gastos_comunidad_eur,orientacion_list,planta_numerica,acepta_mascotas
0,https://www.pisos.com/alquilar/piso-penagrande...,5.507919e+10,Peñagrande,Fuencarral-El Pardo,40.475590,-3.719341,2025-06-16T17:51:59.469159,31Real Servicios Inmobiliarios alquila moderno...,Pendiente de completar,NaN,...,True,False,False,1500.0,NaN,NaN,NaN,['N'],1.0,NaN
1,https://www.pisos.com/alquilar/piso-penagrande...,5.500978e+10,Peñagrande,Fuencarral-El Pardo,40.472500,-3.718590,2025-06-16T17:52:02.329418,31Real Servicios Inmobiliarios presenta este e...,Pendiente de completar,NaN,...,True,False,False,1800.0,NaN,NaN,NaN,['SO'],5.0,NaN
2,https://www.pisos.com/alquilar/piso-penagrande...,5.509968e+10,Peñagrande,Fuencarral-El Pardo,40.473300,-3.716480,2025-06-16T17:52:04.222347,31real servicios inmobiliarios alquila viviend...,Pendiente de completar,NaN,...,False,True,False,1600.0,NaN,NaN,NaN,['S'],8.0,NaN
3,https://www.pisos.com/alquilar/piso-recoletos2...,5.342772e+10,Recoletos,Salamanca,40.422300,-3.680950,2025-06-16T17:52:06.371839,222m / 4 dormitorios / 4 Baños / Trastero / Po...,Disponible,E,...,False,True,False,7750.0,189.0,39.0,NaN,['NO'],3.0,NaN
4,https://www.pisos.com/alquilar/piso-chamberi_a...,5.253707e+10,Arapiles,Chamberí,40.436190,-3.705911,2025-06-16T17:52:08.229176,ALQUILER TEMPORAL DISPONIBLE DESDE EL 01 DE JU...,Disponible,F,...,False,False,False,1000.0,306.0,58.0,NaN,NaN,2.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2309,https://www.pisos.com/alquilar/piso-el_soto_de...,5.509143e+10,NaN,NaN,40.521954,-3.648517,2025-06-16T19:04:21.811131,La Inmobiliaria Internacional CPM gestiona est...,Pendiente de completar,NaN,...,True,True,False,4200.0,NaN,NaN,NaN,['S'],2.0,True
2310,https://www.pisos.com/alquilar/piso-el_soto_de...,5.092987e+10,NaN,NaN,40.519891,-3.642340,2025-06-16T19:04:23.606942,Este impresionante piso en alquiler se encuent...,En trámite,NaN,...,True,True,True,5500.0,NaN,NaN,NaN,NaN,1.0,NaN
2311,https://www.pisos.com/alquilar/piso-la_moralej...,5.425132e+10,NaN,NaN,40.507050,-3.624863,2025-06-16T19:04:25.420831,Gilmar pone a su disposición este excelente pi...,En trámite,NaN,...,False,False,False,4750.0,NaN,NaN,NaN,NaN,NaN,NaN
2312,https://www.pisos.com/alquilar/piso-el_soto_de...,5.252304e+10,NaN,NaN,40.520302,-3.642174,2025-06-16T19:04:27.269042,MAGNAPOL ALQUILA en EXCLUSIVA Amplio piso . 30...,En trámite,NaN,...,True,True,True,5000.0,NaN,NaN,NaN,['SE'],1.0,True
2313,https://www.pisos.com/alquilar/piso-el_soto_de...,5.086650e+10,NaN,NaN,40.519583,-3.640506,2025-06-16T19:04:29.157385,¡Descubre el hogar de tus sueños en una de las...,En trámite,NaN,...,True,True,True,4400.0,NaN,NaN,NaN,['E'],0.0,NaN

Normalizamos campos comunes

In [10]:
df_rental['listing_type'] = 'rental'
df_rental['price_kind']  = 'rent_month'
df_rental['price_eur']   = df_rental['price_eur_pm']
df_sale  ['listing_type'] = 'sale'
df_sale  ['price_kind']   = 'sale_price'

In [15]:
df_sale['acepta_mascotas'] = None

In [13]:
common_cols = [
    'property_id','url','listing_type','price_kind','price_eur','scraped_at','description',
    'barrio','distrito','latitude','longitude',
    'superficie_construida','superficie_util','habitaciones','banos','planta_numerica',
    'antiguedad','conservacion','energy_cert_classification',
    'energy_consumption_rating','energy_emissions_rating',
    'energy_consumption_kwh_m2_yr','energy_emissions_kg_co2_m2_yr',
    # boolean features:
    'ascensor','balcon','calefaccion','chimenea','cocina_equipada','exterior','garaje',
    'jardin','piscina','trastero','terraza','adaptado_movilidad_reducida',
    'aire_acondicionado','puerta_blindada','vidrios_dobles','sistema_seguridad',
    'acepta_mascotas'  # política mascotas unificada
]

In [16]:
df_rental = df_rental[common_cols]
df_sale   = df_sale[common_cols]

In [17]:
df_all = pd.concat([df_rental, df_sale], ignore_index=True)

In [18]:
df_all

,property_id,url,listing_type,price_kind,price_eur,scraped_at,description,barrio,distrito,latitude,...,jardin,piscina,trastero,terraza,adaptado_movilidad_reducida,aire_acondicionado,puerta_blindada,vidrios_dobles,sistema_seguridad,acepta_mascotas
0,5.507919e+10,https://www.pisos.com/alquilar/piso-penagrande...,rental,rent_month,1500.0,2025-06-16T17:51:59.469159,31Real Servicios Inmobiliarios alquila moderno...,Peñagrande,Fuencarral-El Pardo,40.475590,...,True,True,False,True,False,True,False,False,False,NaN
1,5.500978e+10,https://www.pisos.com/alquilar/piso-penagrande...,rental,rent_month,1800.0,2025-06-16T17:52:02.329418,31Real Servicios Inmobiliarios presenta este e...,Peñagrande,Fuencarral-El Pardo,40.472500,...,True,False,False,True,False,True,False,False,False,NaN
2,5.509968e+10,https://www.pisos.com/alquilar/piso-penagrande...,rental,rent_month,1600.0,2025-06-16T17:52:04.222347,31real servicios inmobiliarios alquila viviend...,Peñagrande,Fuencarral-El Pardo,40.473300,...,False,False,True,False,False,True,False,False,False,NaN
3,5.342772e+10,https://www.pisos.com/alquilar/piso-recoletos2...,rental,rent_month,7750.0,2025-06-16T17:52:06.371839,222m / 4 dormitorios / 4 Baños / Trastero / Po...,Recoletos,Salamanca,40.422300,...,False,False,True,False,False,True,True,False,False,NaN
4,5.253707e+10,https://www.pisos.com/alquilar/piso-chamberi_a...,rental,rent_month,1000.0,2025-06-16T17:52:08.229176,ALQUILER TEMPORAL DISPONIBLE DESDE EL 01 DE JU...,Arapiles,Chamberí,40.436190,...,False,False,False,False,False,True,False,False,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5289,5.339863e+10,https://www.pisos.com/comprar/piso-pilar28029-...,sale,sale_price,290000.0,2025-06-16T20:41:52.935318,Nmobiliaria tecnocasa barrio del pilar-la vagu...,Pilar,Fuencarral-El Pardo,40.478543,...,False,False,False,True,False,False,False,False,False,None
5290,5.084455e+10,https://www.pisos.com/comprar/piso-goya28009-5...,sale,sale_price,1300000.0,2025-06-16T20:41:54.731735,*Las imágenes de las estancias amuebladas y de...,Goya,Salamanca,40.424744,...,False,False,False,False,False,False,True,False,False,None
5291,4.756165e+10,https://www.pisos.com/comprar/apartamento-goya...,sale,sale_price,1800000.0,2025-06-16T20:41:56.595975,"Engel & Völkers, inmobiliaria de lujo, tiene e...",Goya,Salamanca,40.421674,...,False,False,False,False,False,False,False,False,False,None
5292,4.587160e+10,https://www.pisos.com/comprar/atico-universida...,sale,sale_price,1080000.0,2025-06-16T20:41:58.381915,Fortuny Real Estate ofrece ático de lujo a est...,Universidad-Malasaña,Centro,40.425055,...,False,True,False,True,False,False,False,False,False,None
5293,5.418658e+10,https://www.pisos.com/comprar/apartamento-reco...,sale,sale_price,2309000.0,2025-06-16T20:42:00.278871,Engel & Völkers tiene el placer de presentar e...,Recoletos,Salamanca,40.425238,...,False,False,False,False,False,False,False,False,False,None

Mapeo de url con listing_id y native_id con property_id

In [23]:
cursor.execute("SELECT url,listing_id FROM listing")

In [24]:
map_list = { url: lid for url, lid in cursor.fetchall() }

In [ ]:
# mapeamos URL → listing_id
map_list

{'https://www.pisos.com/alquilar/atico-salamanca_castellana28006-51740663097_108900/': 1,
 'https://www.pisos.com/alquilar/atico-rio_rosas28003-54233688682_108900/': 2,
 'https://www.pisos.com/alquilar/piso-salamanca_castellana28006-54235652798_108900/': 3,
 'https://www.pisos.com/alquilar/piso-fuente_del_berro28028-575224267_440000/': 4,
 'https://www.pisos.com/alquilar/piso-justicia_chueca28004-52524614200_100500/': 5,
 'https://www.pisos.com/alquilar/piso-moncloa_aravaca_aravaca28023-45072351463_101800/': 6,
 'https://www.pisos.com/alquilar/apartamento-rejas28022-54187238191_101000/': 7,
 'https://www.pisos.com/alquilar/estudio-justicia_chueca28004-50050215109_992227/': 8,
 'https://www.pisos.com/alquilar/piso-berruguete28039-53383290265_100500/': 9,
 'https://www.pisos.com/alquilar/piso-san_blas_simancas28037-54200622147_104700/': 10,
 'https://www.pisos.com/alquilar/piso-ibiza28009-47548601877_109100/': 11,
 'https://www.pisos.com/alquilar/piso-justicia_chueca28004-49205237030_528374/': 12,
 'https://www.pisos.com/alquilar/chalet_adosado-mirasierra_arroyo_del_fresno28035-51733423042_520609/': 13,
 'https://www.pisos.com/alquilar/piso-lista_barrio28006-54170213820_998146/': 14,
 'https://www.pisos.com/alquilar/piso-recoletos28001-99231398150_101800/': 15,
 'https://www.pisos.com/alquilar/atico-recoletos28001-53358152643_528426/': 16,
 'https://www.pisos.com/alquilar/piso-salamanca_castellana28006-51716059612_149200/': 17,
 'https://www.pisos.com/alquilar/piso-carabanchel_buenavista28044-53389624349_996848/': 18,
 'https://www.pisos.com/alquilar/piso-puerta_del_angel-54195192843_104700/': 19,
 'https://www.pisos.com/alquilar/piso-pinar_del_rey28033-52514594158_101800/': 20,
 'https://www.pisos.com/alquilar/piso-justicia_chueca28004-54244337317_101800/': 21,
 'https://www.pisos.com/alquilar/piso-chamartin_el_viso28002-53412347550_101800/': 22,
 'https://www.pisos.com/alquilar/piso-atocha28045-4754653103_109700/': 23,
 'https://www.pisos.com/alquilar/estudio-chamberi_almagro28010-42500841809_522531/': 24,
 'https://www.pisos.com/alquilar/piso-penagrande28035-52559515484_521139/': 25,
 'https://www.pisos.com/alquilar/piso-nino_jesus28009-42589943480_100500/': 26,
 'https://www.pisos.com/alquilar/piso-barrio_de_salamanca_castellana28006-52512076268_149200/': 27,
 'https://www.pisos.com/alquilar/piso-imperial28005-52548342025_529055/': 28,
 'https://www.pisos.com/alquilar/piso-san_blas_simancas28037-54257013451_100500/': 29,
 'https://www.pisos.com/alquilar/piso-puerta_del_angel-54194276697_104700/': 30,
 'https://www.pisos.com/alquilar/piso-mirasierra_arroyo_del_fresno28034-21725441885_101800/': 31,
 'https://www.pisos.com/alquilar/atico-trafalgar28004-42513883264_100500/': 32,
 'https://www.pisos.com/alquilar/piso-centro_palacio28013-43408743842_996542/': 33,
 'https://www.pisos.com/alquilar/atico-valdeacederas28039-54174200941_100500/': 34,
 'https://www.pisos.com/alquilar/piso-retiro_estrella28007-53370434507_100500/': 35,
 'https://www.pisos.com/alquilar/piso-trafalgar28010-45878156825_100500/': 36,
 'https://www.pisos.com/alquilar/piso-el_canaveral-4884840136_109700/': 37,
 'https://www.pisos.com/alquilar/piso-centro_palacio28013-51717819667_100500/': 38,
 'https://www.pisos.com/alquilar/piso-chamberi_almagro28010-40836185945_100500/': 39,
 'https://www.pisos.com/alquilar/piso-chopera28045-54199273174_100200/': 40,
 'https://www.pisos.com/alquilar/piso-jeronimos28014-45905910548_100500/': 41,
 'https://www.pisos.com/alquilar/piso-barrio_de_salamanca_castellana28001-52513928669_996542/': 42,
 'https://www.pisos.com/alquilar/piso-chamberi_arapiles28015-52537066986_100200/': 43,
 'https://www.pisos.com/alquilar/piso-chamartin_el_viso28002-52518856388_100500/': 44,
 'https://www.pisos.com/alquilar/estudio-tetuan_cuatro_caminos28020-48356304845_996542/': 45,
 'https://www.pisos.com/alquilar/piso-centro_palacio28013-40917563853_996542/': 46,
 'https://www.pisos.com/alquilar/piso-tetuan_almenara28029-50860299692_996542/': 47,
 'https://www.pisos.com/alquilar/piso-justicia_chueca28004-42520786919_109300/': 48,
 'https://www.pisos.com/alquilar/estudio-tetuan_almenara28029-49215335540_996542/': 49,
 'https://www.pisos.com/alquilar/piso-imperial28005-43383484081_100200/': 50,
 'https://www.pisos.com/alquilar/piso-moncloa_aravaca_aravaca28023-53377592364_100500/': 51,
 'https://www.pisos.com/alquilar/piso-lista_barrio28006-43415878566_996542/': 52,
 'https://www.pisos.com/alquilar/piso-opanel28019-54228189273_520820/': 53,
 'https://www.pisos.com/alquilar/piso-ciudad_lineal_san_pascual28027-53390153377_100200/': 54,
 'https://www.pisos.com/alquilar/atico-universidad_malasana28004-46718662002_100500/': 55,
 'https://www.pisos.com/alquilar/piso-concepcion-92580015400_514429/': 56,
 'https://www.pisos.com/alquilar/piso-salamanca_castellana28006-927068487_996542/': 57,
 'https://www.pisos.com/alquilar/piso-barrio_de_salamanca_castellana28006-42533163729_100500/': 58,
 'https://www.pisos.com/alquilar/piso-puerta_bonita28025-54217758501_105700/': 59,
 'https://www.pisos.com/alquilar/piso-chamberi_almagro28010-51725235515_106000/': 60,
 'https://www.pisos.com/alquilar/apartamento-concepcion28027-52552907761_101000/': 61,
 'https://www.pisos.com/alquilar/piso-gaztambide28015-30000292679_100500/': 62,
 'https://www.pisos.com/alquilar/piso-palos_de_moguer28045-13401653773_100500/': 63,
 'https://www.pisos.com/alquilar/piso-bellas_vistas28039-54246001591_100200/': 64,
 'https://www.pisos.com/alquilar/piso-centro_palacio28005-45915956478_100900/': 65,
 'https://www.pisos.com/alquilar/piso-centro_embajadores_lavapies28012-54215452780_100500/': 66,
 'https://www.pisos.com/alquilar/piso-chamartin_hispanoamerica28036-49241736431_100500/': 67,
 'https://www.pisos.com/alquilar/piso-ventas28017-54202477846_996957/': 68,
 'https://www.pisos.com/alquilar/piso-centro_embajadores_lavapies28012-52577820888_100200/': 69,
 'https://www.pisos.com/alquilar/piso-nueva_espana28036-49192896228_996542/': 70,
 'https://www.pisos.com/alquilar/estudio-san_blas_hellin28037-47594817671_518978/': 71,
 'https://www.pisos.com/alquilar/piso-centro_embajadores_lavapies28012-53360687025_100200/': 72,
 'https://www.pisos.com/alquilar/piso-moncloa_aravaca_arguelles28008-54205096826_100200/': 73,
 'https://www.pisos.com/alquilar/piso-corralejos28042-54237946059_100200/': 74,
 'https://www.pisos.com/alquilar/estudio-ciudad_lineal_pueblo_nuevo28017-15882091149_518978/': 75,
 'https://www.pisos.com/alquilar/piso-imperial28011-53393551864_100500/': 76,
 'https://www.pisos.com/alquilar/apartamento-sol_barrio28012-46738387641_519303/': 77,
 'https://www.pisos.com/alquilar/piso-penagrande28035-54191959053_101800/': 78,
 'https://www.pisos.com/alquilar/piso-fuencarral_el_pardo_la_paz28034-52579715002_100500/': 79,
 'https://www.pisos.com/alquilar/piso-ensanche_de_vallecas_valdecarros28051-54256635364_108900/': 80,
 'https://www.pisos.com/alquilar/piso-trafalgar28010-50035325651_100500/': 81,
 'https://www.pisos.com/alquilar/piso-fuencarral_el_pardo_la_paz28029-52582495123_101000/': 82,
 'https://www.pisos.com/alquilar/piso-chamartin_el_viso28036-19260801217_517093/': 83,
 'https://www.pisos.com/alquilar/piso-carabanchel_san_isidro28019-50881294258_108900/': 84,
 'https://www.pisos.com/alquilar/chalet-valdezarza28035-52539810238_100500/': 85,
 'https://www.pisos.com/alquilar/piso-valdeacederas28029-54258431741_103800/': 86,
 'https://www.pisos.com/alquilar/piso-guindalera28028-52548351506_108500/': 87,
 'https://www.pisos.com/alquilar/piso-rios_rosas28003-52519131206_108900/': 88,
 'https://www.pisos.com/alquilar/piso-hortaleza_canillas28043-49257493361_108900/': 89,
 'https://www.pisos.com/alquilar/piso-rios_rosas28003-51679213939_108900/': 90,
 'https://www.pisos.com/alquilar/piso-tetuan_almenara28046-54175654836_108900/': 91,
 'https://www.pisos.com/alquilar/piso-hortaleza_canillas28043-49231344199_108900/': 92,
 'https://www.pisos.com/alquilar/piso-piovera28043-52594308155_108900/': 93,
 'https://www.pisos.com/alquilar/piso-piovera28043-52511371793_108900/': 94,
 'https://www.pisos.com/alquilar/piso-penagrande28035-54202533932_108900/': 95,
 'https://www.pisos.com/alquilar/piso-goya28009-52553982466_108500/': 96,
 'https://www.pisos.com/alquilar/apartamento-casco_historico_de_barajas-44244362736_101800/': 97,
 'https://www.pisos.com/alquilar/piso-piovera28043-52583584363_108900/': 98,
 'https://www.pisos.com/alquilar/piso-chamartin_hispanoamerica28016-51694842591_101800/': 99,
 'https://www.pisos.com/alquilar/piso-guindalera28028-52536690855_108900/': 100,
 'https://www.pisos.com/alquilar/piso-tetuan_almenara28029-54192780136_108900/': 101,
 'https://www.pisos.com/alquilar/atico-sanchinarro28050-43379253317_100500/': 102,
 'https://www.pisos.com/alquilar/piso-arganzuela_delicias-54226085766_108900/': 103,
 'https://www.pisos.com/alquilar/casa_adosada-valdebebas_valdefuentes28055-51758787666_100500/': 104,
 'https://www.pisos.com/alquilar/piso-chamartin_hispanoamerica28016-49222438027_108900/': 105,
 'https://www.pisos.com/alquilar/piso-ciudad_lineal_san_pascual28027-52514095655_108900/': 106,
 'https://www.pisos.com/alquilar/piso-puerta_del_angel-52534198400_108900/': 107,
 'https://www.pisos.com/alquilar/apartamento-trafalgar28010-38406054757_101800/': 108,
 'https://www.pisos.com/alquilar/piso-piovera28043-54232736716_108900/': 109,
 'https://www.pisos.com/alquilar/piso-goya28009-52584680554_108900/': 110,
 'https://www.pisos.com/alquilar/piso-puerta_del_angel-52590589136_108900/': 111,
 'https://www.pisos.com/alquilar/piso-hortaleza_canillas28043-53415970602_108900/': 112,
 'https://www.pisos.com/alquilar/piso-goya28001-51763164773_108900/': 113,
 'https://www.pisos.com/alquilar/estudio-bellas_vistas28039-52579688901_108900/': 114,
 'https://www.pisos.com/alquilar/piso-penagrande28035-53349195674_108900/': 115,
 'https://www.pisos.com/alquilar/piso-legazpi_barrio28045-54221453468_108900/': 116,
 'https://www.pisos.com/alquilar/piso-piovera28043-54232360310_108900/': 117,
 'https://www.pisos.com/alquilar/apartamento-bellas_vistas28039-52509880125_101800/': 118,
 'https://www.pisos.com/alquilar/piso-universidad_malasana28004-51762502410_108500/': 119,
 'https://www.pisos.com/alquilar/piso-piovera28043-54172612130_108900/': 120,
 'https://www.pisos.com/alquilar/piso-legazpi_barrio28045-52563908587_108900/': 121,
 'https://www.pisos.com/alquilar/apartamento-rios_rosas28003-46745207350_101800/': 122,
 'https://www.pisos.com/alquilar/piso-ciudad_lineal_san_pascual28027-52517245130_108900/': 123,
 'https://www.pisos.com/alquilar/piso-butarque28021-52599970631_108900/': 124,
 'https://www.pisos.com/alquilar/piso-guindalera28028-54170197971_108900/': 125,
 'https://www.pisos.com/alquilar/piso-ensanche_de_vallecas_valdecarros28051-49258955300_108900/': 126,
 'https://www.pisos.com/alquilar/piso-chamartin_ciudad_jardin28002-52582241240_108500/': 127,
 'https://www.pisos.com/alquilar/apartamento-goya28009-52523960996_101800/': 128,
 'https://www.pisos.com/alquilar/apartamento-centro_palacio28013-50835038645_101800/': 129,
 'https://www.pisos.com/alquilar/piso-guindalera28028-54227493387_108900/': 130,
 'https://www.pisos.com/alquilar/atico-el_canaveral-40900638027_100500/': 131,
 'https://www.pisos.com/alquilar/piso-penagrande28035-53387616042_108900/': 132,
 'https://www.pisos.com/alquilar/estudio-lucero28047-52549302124_108900/': 133,
 'https://www.pisos.com/alquilar/piso-chamartin_hispanoamerica28016-51682995645_108500/': 134,
 'https://www.pisos.com/alquilar/piso-hortaleza_canillas28043-54184679213_108900/': 135,
 'https://www.pisos.com/alquilar/piso-chamartin_hispanoamerica28016-52553596125_108900/': 136,
 'https://www.pisos.com/alquilar/apartamento-chamberi_arapiles28015-52504627456_101800/': 137,
 'https://www.pisos.com/alquilar/piso-recoletos28001-51721094916_108500/': 138,
 'https://www.pisos.com/alquilar/piso-piovera28043-50040726462_108900/': 139,
 'https://www.pisos.com/alquilar/piso-chamartin_prosperidad28043-52579735237_102100/': 140,
 'https://www.pisos.com/alquilar/apartamento-guindalera28028-49169967892_101800/': 141,
 'https://www.pisos.com/alquilar/atico-goya28028-51731880754_108500/': 142,
 'https://www.pisos.com/alquilar/apartamento-recoletos28001-52570728125_101800/': 143,
 'https://www.pisos.com/alquilar/piso-hortaleza_canillas28043-53381762972_108900/': 144,
 'https://www.pisos.com/alquilar/piso-rios_rosas28003-51754011937_108500/': 145,
 'https://www.pisos.com/alquilar/piso-imperial28005-52513867385_109300/': 146,
 'https://www.pisos.com/alquilar/piso-guindalera28028-54169400780_108900/': 147,
 'https://www.pisos.com/alquilar/piso-timon28042-51751453971_108900/': 148,
 'https://www.pisos.com/alquilar/apartamento-guindalera28028-52506614300_101800/': 149,
 'https://www.pisos.com/alquilar/piso-centro_palacio28005-51685328004_102100/': 150,
 'https://www.pisos.com/alquilar/piso-centro_palacio28005-40908961964_102100/': 151,
 'https://www.pisos.com/alquilar/piso-cortes_huertas28012-35854195146_440000/': 152,
 'https://www.pisos.com/alquilar/piso-cortes_huertas28014-53385306553_996082/': 153,
 'https://www.pisos.com/alquilar/apartamento-gaztambide28003-52544651614_100500/': 154,
 'https://www.pisos.com/alquilar/piso-castilla28046-53372221658_524612/': 155,
 'https://www.pisos.com/alquilar/piso-retiro_pacifico28014-54240908780_100500/': 156,
 'https://www.pisos.com/alquilar/estudio-nueva_espana28036-54175210805_106000/': 157,
 'https://www.pisos.com/alquilar/apartamento-bellas_vistas28039-39229612489_527206/': 158,
 'https://www.pisos.com/alquilar/piso-corralejos28042-54230786832_528332/': 159,
 'https://www.pisos.com/alquilar/piso-justicia_chueca28004-51713284831_100500/': 160,
 'https://www.pisos.com/alquilar/piso-recoletos28001-50894863614_995410/': 161,
 'https://www.pisos.com/alquilar/piso-san_blas_simancas28037-54201091029_100500/': 162,
 'https://www.pisos.com/alquilar/piso-centro_palacio28005-54181526080_528990/': 163,
 'https://www.pisos.com/alquilar/piso-chamartin_el_viso28002-53388916436_100500/': 164,
 'https://www.pisos.com/alquilar/piso-ciudad_universitaria28040-54203083047_104700/': 165,
 'https://www.pisos.com/alquilar/apartamento-pau_de_carabanchel28054-54241832789_100500/': 166,
 'https://www.pisos.com/alquilar/piso-chamberi_arapiles28015-53333677923_521707/': 167,
 'https://www.pisos.com/alquilar/piso-rio_rosas28003-54244406295_104700/': 168,
 'https://www.pisos.com/alquilar/estudio-valdeacederas28029-54186692776_500564/': 169,
 'https://www.pisos.com/alquilar/piso-lista_barrio28006-53420593737_109300/': 170,
 'https://www.pisos.com/alquilar/piso-ibiza28009-54173055675_101000/': 171,
 'https://www.pisos.com/alquilar/apartamento-sanchinarro28050-54245098062_992099/': 172,
 'https://www.pisos.com/alquilar/piso-justicia_chueca28004-52546728652_100500/': 173,
 'https://www.pisos.com/alquilar/piso-trafalgar28015-53338030276_108900/': 174,
 'https://www.pisos.com/alquilar/piso-recoletos28009-53427720365_100500/': 175,
 'https://www.pisos.com/alquilar/piso-moncloa_aravaca_arguelles28008-54227227184_520252/': 176,
 'https://www.pisos.com/alquilar/piso-ibiza28009-52578158619_992439/': 177,
 'https://www.pisos.com/alquilar/piso-chamberi_arapiles28015-54184646314_521737/': 178,
 'https://www.pisos.com/alquilar/piso-sol_barrio28012-49211439174_529055/': 179,
 'https://www.pisos.com/alquilar/piso-universidad_malasana28015-5916835829_100500/': 180,
 'https://www.pisos.com/alquilar/apartamento-chamartin_hispanoamerica28036-5071111647_100100/': 181,
 'https://www.pisos.com/alquilar/piso-palos_de_moguer28045-54232882656_100500/': 182,
 'https://www.pisos.com/alquilar/piso-goya28001-54194614476_100500/': 183,
 'https://www.pisos.com/alquilar/piso-nueva_espana28016-54187060207_100500/': 184,
 'https://www.pisos.com/alquilar/estudio-castillejos28046-51727752541_529113/': 185,
 'https://www.pisos.com/alquilar/piso-guindalera28028-52565225980_520919/': 186,
 'https://www.pisos.com/alquilar/piso-rio_rosas28003-54198012909_106000/': 187,
 'https://www.pisos.com/alquilar/piso-pilar28029-54199552503_101000/': 188,
 'https://www.pisos.com/alquilar/piso-chamberi_vallehermoso28003-54242504676_991150/': 189,
 'https://www.pisos.com/alquilar/piso-castilla28046-50919331170_522531/': 190,
 'https://www.pisos.com/alquilar/piso-retiro_pacifico28007-52566687472_100500/': 191,
 'https://www.pisos.com/alquilar/piso-fuente_del_berro28028-54194261727_100500/': 192,
 'https://www.pisos.com/alquilar/piso-imperial28005-29228616576_512906/': 193,
 'https://www.pisos.com/alquilar/estudio-pinar_del_rey28033-54210781558_100500/': 194,
 'https://www.pisos.com/alquilar/piso-lucero28011-54215706355_101800/': 195,
 'https://www.pisos.com/alquilar/piso-chamberi_vallehermoso28003-54233497766_101000/': 196,
 'https://www.pisos.com/alquilar/piso-el_canaveral-4921479272_109700/': 197,
 'https://www.pisos.com/alquilar/piso-el_canaveral-26687314036_525162/': 198,
 'https://www.pisos.com/alquilar/apartamento-casa_de_campo28011-53371311428_100900/': 199,
 'https://www.pisos.com/alquilar/piso-el_canaveral-4884049270_109700/': 200,
 'https://www.pisos.com/alquilar/piso-san_blas_canillejas28022-54241837864_104700/': 201,
 'https://www.pisos.com/alquilar/piso-ibiza28009-54234959135_100500/': 202,
 'https://www.pisos.com/alquilar/piso-atocha28045-4683894822_109700/': 203,
 'https://www.pisos.com/alquilar/piso-ibiza28009-53430060005_100500/': 204,
 'https://www.pisos.com/alquilar/piso-moncloa_aravaca_arguelles28008-54204553672_108500/': 205,
 'https://www.pisos.com/alquilar/duplex-usera_pradolongo28026-54260491201_108900/': 206,
 'https://www.pisos.com/alquilar/atico-justicia_chueca28004-945856909480201_109700/': 207,
 'https://www.pisos.com/alquilar/piso-nino_jesus28009-54223390634_101000/': 208,
 'https://www.pisos.com/alquilar/apartamento-barrio_de_salamanca_lista28006-52563343176_100500/': 209,
 'https://www.pisos.com/alquilar/apartamento-centro_embajadores_lavapies28005-52546947727_992238/': 210,
 'https://www.pisos.com/alquilar/piso-justicia_chueca-54183545393_106600/': 211,
 'https://www.pisos.com/alquilar/apartamento-centro_embajadores_lavapies28005-53342699330_515335/': 212,
 'https://www.pisos.com/alquilar/piso-lista_barrio28006-54176927123_106000/': 213,
 'https://www.pisos.com/alquilar/atico-universidad_malasana-54171575727_106600/': 214,
 'https://www.pisos.com/alquilar/apartamento-chamberi_almagro28010-40846279329_527206/': 215,
 'https://www.pisos.com/alquilar/loft-sol_barrio28013-39265841354_527206/': 216,
 'https://www.pisos.com/alquilar/apartamento-universidad_malasana28004-40933041284_527206/': 217,
 'https://www.pisos.com/alquilar/atico-salamanca_castellana28006-36765986119_995410/': 218,
 'https://www.pisos.com/alquilar/duplex-valdezarza28035-40901566427_527206/': 219,
 'https://www.pisos.com/alquilar/estudio-numancia28038-39198640641_527206/': 220,
 'https://www.pisos.com/alquilar/piso-trafalgar28010-53405475325_440000/': 221,
 'https://www.pisos.com/alquilar/piso-chamberi_arapiles28015-18366550285_100500/': 222,
 'https://www.pisos.com/alquilar/duplex-chamberi_almagro28003-39191654458_527206/': 223,
 'https://www.pisos.com/alquilar/piso-penagrande-54197258976_106600/': 224,
 'https://www.pisos.com/alquilar/piso-chamartin_el_viso28002-25092626009_100500/': 225,
 'https://www.pisos.com/alquilar/piso-centro_embajadores_lavapies28012-35846408273_100500/': 226,
 'https://www.pisos.com/alquilar/piso-goya28009-49183841731_528973/': 227,
 'https://www.pisos.com/alquilar/piso-justicia_chueca28004-45833694266_100500/': 228,
 'https://www.pisos.com/alquilar/piso-centro_palacio28013-35043837312_100500/': 229,
 'https://www.pisos.com/alquilar/piso-guindalera28028-43416032093_440000/': 230,
 'https://www.pisos.com/alquilar/piso-valdemarin-45072478244_101800/': 231,
 'https://www.pisos.com/alquilar/apartamento-bellas_vistas28039-39173847142_527206/': 232,
 'https://www.pisos.com/alquilar/piso-valdezarza28035-45021521231_101800/': 233,

In [26]:
cursor.execute("SELECT property_native_id,property_id FROM property")

In [27]:
map_prop = { pid: propid for pid, propid in cursor.fetchall() }

In [29]:
# mapeamos native_id → property_id
map_prop

{'11683122104.1001': 4156,
 '11713976246.1005': 3059,
 '12520879287.996542': 789,
 '13384785496.996542': 705,
 '13401653773.1005': 63,
 '15065560922.996542': 769,
 '15091421027.1021': 2005,
 '15094991482.996542': 737,
 '15882091149.518978': 75,
 '16755127185.1005': 1119,
 '16755913201.516598': 780,
 '1676213431.996542': 881,
 '17500082181.1005': 756,
 '1750037059.996542': 845,
 '17598322130.1005': 250,
 '1772946757.1097': 2666,
 '18366550285.1005': 222,
 '19168697534.517094': 4060,
 '19173521149.517094': 4556,
 '19178660789.517094': 4346,
 '19197237241.996544': 4259,
 '19199665125.517094': 4237,
 '19220092216.517094': 934,
 '19240687566.51897': 938,
 '19260801217.517094': 83,
 '19261761023.517094': 1033,
 '20006412977.996544': 753,
 '20041996024.1092': 279,
 '20049394249.1005': 1497,
 '20057768451.1005': 1027,
 '20084069014.1092': 344,
 '20839223003.1492': 3116,
 '20905432544.52015': 5102,
 '21670182341.1005': 1395,
 '21711813995.1005': 1256,
 '21725441885.1018': 31,
 '21727250593.519302': 3994,
 '22506447503.1005': 1226,
 '22515876767.1021': 4594,
 '22595288263.996544': 626,
 '23349238793.1005': 3960,
 '23375522103.1018': 840,
 '23397469114.1005': 3492,
 '23406721431.996544': 3854,
 '23418933460.1089': 1998,
 '24173811167.517094': 4635,
 '24176894216.1005': 246,
 '24178797472.996544': 4046,
 '24220431095.1005': 4746,
 '24238664856.996544': 4103,
 '24242124129.1005': 1759,
 '24243937754.1021': 4153,
 '24254001404.1005': 296,
 '24254231384.996544': 717,
 '25020522818.996544': 489,
 '25029072185.517094': 4034,
 '25044764716.1005': 1174,
 '25051116368.996544': 3848,
 '25092626009.1005': 225,
 '25841208511.1002': 3985,
 '25843393551.1005': 3201,
 '25862375777.1021': 3542,
 '25864669701.51572': 287,
 '25869676436.1005': 598,
 '25883283859.1021': 3864,
 '25918194294.1002': 2504,
 '25924279650.1002': 4372,
 '25926867877.1021': 4726,
 '25929329079.1005': 3391,
 '25933298715.1005': 3195,
 '26677372255.1005': 4537,
 '26687314036.52516': 198,
 '26707220816.1005': 806,
 '26715176601.996544': 790,
 '26744409598.1005': 3979,
 '26758456788.1005': 1916,
 '26765671161.1005': 1789,
 '27512115826.1005': 1248,
 '27516275360.1021': 1824,
 '27520178948.1002': 4590,
 '27536509528.5166': 1030,
 '27537100387.996544': 627,
 '27546996052.1005': 1746,
 '27550255772.517094': 4456,
 '27556802667.1021': 3644,
 '27560154573.1018': 2167,
 '27563527218.1002': 2415,
 '27590075802.52015': 4786,
 '28366803305.1005': 4032,
 '28371979661.996544': 606,
 '28402498297.1002': 4299,
 '28420070624.1005': 1837,
 '28425286595.1005': 302,
 '29179587150.996544': 450,
 '29180724817.1005': 2705,
 '29187576498.1005': 4625,
 '29187825553.1005': 1219,
 '29220891458.1005': 1727,
 '29228616576.512905': 193,
 '29234233741.1018': 3832,
 '29254164688.1002': 4145,
 '29258134707.1002': 2400,
 '30000292679.1005': 62,
 '30059425876.1005': 872,
 '30087454107.1005': 4223,
 '30834689400.1018': 2328,
 '30839507776.996544': 3631,
 '30841669025.996544': 771,
 '30846610173.1005': 1723,
 '30861237011.1005': 4492,
 '30880256826.996544': 729,
 '30884125976.1009': 2306,
 '30889935773.1005': 1464,
 '30894025655.1002': 4777,
 '30908434996.1005': 3525,
 '31682869252.1021': 3976,
 '31686987109.1005': 1235,
 '31688271944.1002': 4254,
 '31704926896.1005': 1523,
 '31719218390.1002': 2129,
 '31735727373.1005': 3893,
 '31740395636.1005': 4901,
 '31744941761.996544': 664,
 '31749765096.996544': 785,
 '31755755043.1005': 3822,
 '31759294441.1005': 1801,
 '31764108017.1002': 2642,
 '32511124551.996544': 707,
 '32515324577.1005': 4000,
 '32523387604.1021': 2600,
 '32538909393.1021': 2654,
 '32546683020.996544': 3967,
 '32547580039.1005': 4114,
 '32548920337.1002': 1319,
 '32550522208.1021': 1939,
 '32552168529.1089': 5142,
 '32554760612.1005': 4577,
 '32556036229.996544': 743,
 '32580975434.1005': 4089,
 '32592415097.1002': 4435,
 '33340223536.1002': 2446,
 '33342262918.3813': 4595,
 '33343337686.996544': 667,
 '33346354283.99116': 319,
 '33349644926.1089': 947,
 '33358182214.996544': 3617,
 '33366605299.1005': 4441,
 '33367760465.517094': 4811,
 '33371959042.996544': 3909,
 '33373252127.996544': 3792,
 '33387004415.1089': 1738,
 '33393243437.996544': 762,
 '33401115280.99116': 345,
 '33403951288.526302': 2918,
 '33405592202.517094': 4973,
 '33412666111.1002': 3996,
 '33422781488.996544': 655,
 '33432561339.1492': 3280,
 '34167213391.1005': 3393,
 '34180598783.996544': 3655,
 '34181226285.1021': 3651,
 '34186836003.1005': 1999,
 '34207467533.1021': 2020,
 '34215883128.1005': 4328,
 '34228045552.1005': 1520,
 '34230916936.996544': 4522,
 '34260298105.1005': 1988,
 '35005608639.1002': 1363,
 '35009503547.1051': 2243,
 '35010964701.1002': 1445,
 '35015182244.1051': 3438,
 '35015683095.996544': 493,
 '35016200793.1005': 5141,
 '35021754580.1005': 1384,
 '35024099605.1005': 1889,
 '35024476444.1005': 2027,
 '35025104456.996544': 624,
 '35041488573.1005': 1907,
 '35043837312.1005': 229,
 '35049318432.51809': 927,
 '35057819165.996544': 4141,
 '35060161144.996544': 774,
 '35061895304.1036': 5122,
 '35067268172.1005': 4820,
 '35080443347.1021': 2007,
 '35082827198.1005': 820,
 '35094984314.996544': 498,
 '35095017640.1021': 1906,
 '35097031102.996544': 550,
 '3548570793.1097': 2380,
 '35840240188.1051': 3814,
 '35844794180.996544': 701,
 '35846408273.1005': 226,
 '35854195146.44': 152,
 '35859266705.996544': 4015,
 '35866813827.1005': 1792,
 '35868782939.1002': 491,
 '35871212794.1067': 2858,
 '35873977900.1018': 3784,
 '35874518535.1005': 4686,
 '35884136893.993645': 4382,
 '35897167770.1005': 865,
 '35906115388.1005': 1763,
 '35931287196.1018': 2364,
 '35933148257.1002': 3767,
 '36670586389.100494': 1001,
 '36686890946.1002': 2204,
 '36691645811.100494': 1143,
 '36707585720.100494': 3647,
 '36715256644.100494': 4804,
 '36715674346.1093': 3870,
 '36731530862.52463': 3582,
 '36759706970.1002': 2425,
 '36765986119.99541': 218,
 '37502500613.1021': 3706,
 '37515189974.107': 4504,
 '37529391889.100494': 887,
 '37530359979.100494': 4228,
 '37535504724.1021': 3661,
 '37537974067.1002': 4173,
 '37541028738.1021': 3598,
 '37541355595.100494': 4450,
 '37558092619.100494': 1810,
 '37558398811.100494': 397,
 '37563341116.996544': 3783,
 '37569107989.1002': 4387,
 '37577932151.1002': 3590,
 '37578903243.107': 4217,
 '37580831167.108894': 3289,
 '37585779973.100494': 4642,
 '37585930827.996544': 713,
 '37586846701.100494': 1640,
 '37591077165.100494': 3809,
 '37595507817.1002': 4982,
 '37599869546.100494': 975,
 '38336235290.1018': 1149,
 '38339644160.1018': 1482,
 '38343396151.100494': 3599,
 '38344489691.100494': 1040,
 '38344986528.108894': 1083,
 '38346419022.996544': 3862,
 '38347401097.1018': 1780,
 '38355275146.1018': 1240,
 '38355320113.108894': 5147,
 '38361203719.1018': 1487,
 '38362879781.1492': 3104,
 '38370467566.100494': 1193,
 '38374046801.1492': 2865,
 '38376611054.1018': 1876,
 '38379977379.996544': 3576,
 '38384716743.1018': 1191,
 '38390051242.996544': 3978,
 '38391699834.108894': 4480,
 '38395182134.1021': 4430,
 '38397144250.1018': 1373,
 '38397852616.1018': 1371,
 '38399777938.1492': 3157,
 '38400315838.107': 4883,
 '38401942335.52721': 236,
 '38403738366.1021': 4017,
 '38404310160.109695': 2602,
 '38404863871.100494': 4166,
 '38406054757.1018': 108,
 '38406785087.100494': 4265,
 '38409154902.513664': 2198,
 '38411800010.1018': 1847,
 '38411952435.1492': 2856,
 '38413095926.100494': 1570,
 '38415896826.1021': 1936,
 '38417161900.1018': 1345,
 '38417316988.101': 4987,
 '38419169264.1018': 1151,
 '38424138496.519295': 4269,
 '38425658275.1492': 2961,
 '38427667709.1018': 1815,
 '38429880369.1018': 1144,
 '38429944580.996544': 742,
 '38430850360.1018': 1420,
 '39167369457.996544': 677,
 '39173847142.52721': 232,
 '39182015759.100494': 4204,
 '39184144604.100494': 2995,
 '39186461710.1492': 3260,
 '39191654458.52721': 223,
 '39193142319.1018': 2295,
 '39198640641.52721': 220,
 '39200075586.1021': 5106,
 '39200448773.100494': 3884,
 '39208107458.108894': 3019,
 '39209092031.1018': 2296,
 '39220359408.1021': 3251,
 '39225162009.1002': 2565,
 '39225600502.100494': 3943,
 '39229612489.52721': 158,
 '39230648340.100494': 1314,
 '39232183806.1091': 2928,
 '39234166817.996544': 3797,
 '39239177761.1021': 3511,
 '39239477829.100494': 812,
 '39243804808.100494': 763,
 '39250546139.100494': 4778,
 '39251128931.100494': 991,
 '39252028451.52721': 258,
 '39254695037.1002': 2577,
 '39260844858.51709': 4006,
 '39263322673.100494': 4972,
 '39264744508.1002': 2514,
 '39265841354.52721': 216,
 '40002070530.100494': 294,
 '40004601791.1002': 2581,
 '40005870390.996544': 736,
 '40015110327.100494': 4177,
 '40031461858.100494': 4337,
 '40034925689.1018': 3185,
 '40038137712.51709': 4208,
 '40038796194.100494': 5066,
 '40043000042.100494': 1513,
 '40047406681.100494': 4862,
 '40049102440.99115': 326,
 '40050154810.996544': 570,
 '40051243738.1002': 2463,
 '40055758279.100494': 3914,
 '40060895767.100494': 1196,
 '40068930661.100494': 3327,
 '40089090800.100494': 4579,
 '40833828339.1021': 3704,
 '40836185945.100494': 39,
 '40836635733.1021': 3816,
 '40844799790.100494': 1558,
 '40845277278.996544': 556,
 '40845633641.52662': 4808,
 '40846279329.52721': 215,
 '40848777002.100494': 3374,
 '40854433070.100494': 1506,
 '40854699641.100494': 4159,
 '40863825819.100494': 1323,
 '40864596460.100494': 2549,
 '40873455034.100494': 950,
 '40874746014.109695': 2542,
 '40890155582.100494': 3974,
 '40897790080.1021': 5039,
 '40898400570.100494': 3102,
 '40899688716.52591': 4142,
 '40900638027.100494': 131,
 '40901566427.52721': 219,
 '40901699776.100494': 2971,
 '40905578125.1021': 3529,
 '40908961964.1021': 151,
 '40916373533.109695': 4513,
 '40917563853.996544': 46,
 '40917865105.101': 3867,
 '40925994709.996544': 675,
 '40926035104.108894': 3078,
 '40933041284.52721': 217,
 '41673523991.1492': 3152,
 '41676119503.519295': 936,
 '41679018014.1018': 4636,
 '41686157711.100494': 4298,
 '41686624395.1021': 5021,
 '41688865994.100494': 4414,
 '41691695190.996544': 787,
 '41701053094.107': 4627,
 '41702027406.1018': 1436,
 '41703159244.9932': 2809,
 '41706180346.996544': 565,
 '41712723185.1021': 2317,
 '41713768435.100494': 4879,
 '41716439550.100494': 3208,
 '41716798177.381294': 4663,
 '41718894646.1794': 4255,
 '41719592126.1492': 2232,
 '41720250600.100494': 4578,
 '41720484223.100494': 1532,
 '41723420078.518974': 1679,
 '41723451447.100494': 362,
 '41724904757.1021': 1711,
 '41731912436.1021': 3508,
 '41732456624.100494': 4184,
 '41733230477.996544': 3664,
 '41734471898.1018': 1829,
 '41734545796.100494': 1318,
 '41738605203.1059': 4772,
 '41739290682.1059': 5131,
 '41744021364.1021': 4278,
 '41744088706.1018': 2466,
 '41744260755.100494': 1204,
 '41746106075.100494': 3344,
 '41749125384.996544': 651,
 '41753302751.1021': 1745,
 '41763207757.1021': 4122,
 '42500465092.100494': 634,
 '42500841809.52253': 24,
 '42501173561.100494': 307,
 '42501492741.100494': 437,
 '42501842570.100494': 3638,
 '42502118561.109695': 2722,
 '42502531310.1091': 3364,
 '42502568361.100494': 428,
 '42502588572.996544': 481,
 '42503469937.100494': 583,
 '42504063947.99453': 2863,
 '42505146717.100494': 365,
 '42506771880.108894': 1891,
 '42507276643.100494': 591,
 '42507420012.100494': 506,
 '42507788916.100494': 423,
 '42508394075.100494': 613,
 '42509311380.100494': 412,
 '42510626717.100494': 310,
 '42510649381.100494': 582,
 '42511016128.100494': 477,
 '42511141975.100494': 364,
 '42512363310.100494': 708,
 '42512713213.100494': 308,
 '42512793732.100494': 324,
 '42513006148.100494': 599,
 '42513477676.100494': 349,
 '42513883264.100494': 32,
 '42514352856.100494': 347,
 '42514864088.100494': 484,
 '42515445318.100494': 612,
 '42515721634.100494': 553,
 '42516410313.100494': 718,
 '42516618466.100494': 331,
 '42516849488.1002': 1074,
 '42516904594.100494': 633,
 '42516933738.100494': 710,
 '42517510165.100494': 328,
 '42518378052.100494': 339,
 '42518854269.100494': 401,
 '42519023138.100494': 545,
 '42519438680.100494': 603,
 '42519707874.100494': 435,
 '42519767883.100494': 439,
 '42520398367.100494': 504,
 '42520513296.100494': 408,
 '42520786919.1093': 48,
 '42521048571.100494': 476,
 '42521535530.100494': 459,
 '42521566077.100494': 482,
 '42522141340.100494': 316,
 '42522425348.100494': 538,
 '42522444122.100494': 542,
 '42522806270.100494': 628,
 '42523443805.100494': 574,
 '42523496885.100494': 410,
 '42523737389.100494': 666,
 '42524599286.100494': 662,
 '42524879298.996544': 526,
 '42526444595.100494': 374,
 '42526699221.100494': 446,
 '42528283560.100494': 523,
 '42528684703.100494': 567,
 '42528802472.100494': 629,
 '42528950323.100494': 533,
 '42530080947.100494': 317,
 '42530592641.100494': 343,
 '42531176428.100494': 555,
 '42531195103.100494': 520,
 '42531579590.100494': 652,
 '42531912745.100494': 502,
 '42531953958.100494': 413,
 '42532284024.100494': 517,
 '42532354329.100494': 561,
 '42532634191.100494': 630,
 '42532656979.100494': 674,
 '42532834884.100494': 332,
 '42532910637.100494': 665,
 '42533163729.100494': 58,
 '42533886684.100494': 309,
 '42534189757.100494': 536,
 '42534303605.100494': 351,
 '42534429870.100494': 719,
 '42535940846.100494': 636,
 '42536959261.100494': 379,
 '42537467599.100494': 418,
 '42537824563.996574': 2749,
 '42537940081.100494': 385,
 '42538592793.100494': 711,
 '42538609474.100494': 572,
 '42538908588.100494': 411,
 '42540770868.100494': 416,
 '42540848664.1002': 738,
 '42542714408.100494': 417,
 '42542745841.100494': 648,
 '42542993323.100494': 448,
 '42543377813.100494': 383,
 '42543392673.100494': 449,
 '42543591927.100494': 622,
 '42543658890.100494': 432,
 '42543703347.100494': 453,
 '42544316642.100494': 478,
 '42544465194.100494': 471,
 '42544701254.100494': 356,
 '42545468452.100494': 740,
 '42545578320.100494': 733,
 '42546211892.100494': 304,
 '42546565274.108894': 2054,
 '42546895819.100494': 405,
 '42547091985.100494': 617,
 '42547611242.100494': 657,
 '42547949334.100494': 341,
 '42547994958.100494': 333,
 '42548047078.100494': 697,
 '42548477657.100494': 434,
 '42548831073.100494': 445,
 '42549086767.100494': 424,
 '42549347151.100494': 466,
 '42549874464.100494': 595,
 '42551288953.100494': 669,
 '42553554478.100494': 313,
 '42554581920.100494': 587,
 '42555147821.100494': 452,
 '42555225853.100494': 605,
 '42555373870.100494': 653,
 '42557089679.100494': 354,
 '42557440814.100494': 592,
 '42558290067.100494': 393,
 '42558676112.100494': 568,
 '42559060181.100494': 433,
 '42559118050.100494': 352,
 '42559206215.100494': 601,
 '42559290063.100494': 528,
 '42559350569.100494': 406,
 '42559566807.100494': 422,
 '42559646990.100494': 438,
 '42559683674.100494': 395,
 '42559872299.100494': 323,
 '42560289027.100494': 563,
 '42561115735.100494': 593,
 '42561562041.100494': 680,
 '42563444550.100494': 494,
 '42563633500.100494': 510,
 '42564134807.100494': 420,
 '42564184242.100494': 505,
 '42564341839.100494': 549,
 '42564735784.100494': 638,
 '42564811263.100494': 430,
 '42565531790.100494': 368,
 '42566602091.100494': 350,
 '42567228841.100494': 431,
 '42567292833.100494': 398,
 '42567370782.100494': 703,
 '42567414209.100494': 531,
 '42569410703.100494': 609,
 '42569597019.100494': 369,
 '42571288718.100494': 659,
 '42571370972.100494': 566,
 '42572361358.100494': 726,
 '42573046662.100494': 472,
 '42573048053.100494': 392,
 '42573118842.100494': 394,
 '42573601452.100494': 359,
 '42573675870.100494': 388,
 '42574389513.100494': 440,
 '42576400891.100494': 490,
 '42576439443.100494': 480,
 '42577089692.100494': 514,
 '42578009500.100494': 518,
 '42578430925.100494': 715,
 '42578597004.100494': 693,
 '42579634232.100494': 321,
 '42579765114.100494': 500,
 '42580908727.100494': 451,
 '42581531736.100494': 575,
 '42581613022.100494': 544,
 '42582768862.100494': 335,
 '42582769152.100494': 415,
 '42584187104.1018': 1721,
 '42584894465.1018': 2315,
 '42585634883.100494': 541,
 '42585822676.100494': 387,
 '42586905446.100494': 725,
 '42587546557.100494': 389,
 '42588139911.100494': 515,
 '42589943480.100494': 26,
 '42590103160.100494': 581,
 '42590201834.100494': 647,
 '42590272502.1002': 4604,
 '42590471767.100494': 535,
 '42591722082.100494': 426,
 '42592092530.100494': 645,
 '42592454409.100494': 516,
 '42593333994.996574': 3014,
 '42593344424.1002': 4613,
 '42594169395.100494': 355,
 '42594441920.1018': 1751,
 '42594895616.100494': 375,
 '42594932071.100494': 373,
 '42595044624.100494': 643,
 '42595356334.100494': 580,
 '42596200756.100494': 3499,
 '42596321511.100494': 3412,
 '42596334141.100494': 409,
 '42596572500.100494': 687,
 '42596676589.1021': 3948,
 '42597387694.100494': 656,
 '42597500540.100494': 564,
 '42598630943.100494': 635,
 '42599889077.100494': 639,
 '43337284149.519295': 811,
 '43338552365.1018': 1160,
 '43339000685.100494': 464,
 '43340450064.100494': 5118,
 '43340592834.52563': 875,
 '43346385944.1018': 1091,
 '43348614874.100494': 330,
 '43348913744.996544': 817,
 '43355510930.100494': 378,
 '43355546599.52435': 2220,
 '43357461881.100494': 425,
 '43359261792.100494': 312,
 '43362413138.100494': 299,
 '43363534900.100494': 3176,
 '43363781160.1018': 1842,
 '43363849255.1002': 4668,
 '43364048564.100494': 465,
 '43365964237.100494': 320,
 '43366692243.52631': 3230,
 '43367035429.100494': 419,
 '43371934175.1018': 1383,
 '43375623723.1002': 640,
 '43377244276.52463': 3539,
 '43379253317.100494': 102,
 '43383484081.1002': 50,
 '43385344748.100494': 578,
 '43385685527.100494': 297,
 '43390312247.1002': 4550,
 '43393858503.1018': 2258,
 '43394572317.1492': 3168,
 '43395803345.100494': 3518,
 '43399916673.52415': 4234,
 '43402277420.100494': 447,
 '43405171464.100494': 641,
 '43407418131.996544': 589,
 '43407630984.519295': 4503,
 '43408743842.996544': 33,
 '43409068844.100494': 611,
 '43409690942.100494': 346,
 '43410344382.51951': 463,
 '43412446554.1002': 4676,
 '43413963461.100494': 390,
 '43414712161.100494': 625,
 '43415139486.100494': 4823,
 '43415878566.996544': 52,
 '43416032093.44': 230,
 '43418015391.1018': 1178,
 '43419484553.100494': 602,
 '43423393431.991165': 833,
 '43424920451.100494': 2038,
 '43425044091.1021': 3889,
 '43426822010.100494': 474,
 '43426916514.1018': 2284,
 '43433010840.100494': 386,
 '44166881943.1018': 1650,
 '44167426734.100494': 5034,
 '44169397215.100494': 1169,
 '44172157379.1018': 1264,
 '44174141507.1492': 3071,
 '44174143157.100494': 4770,
 '44177985665.1093': 283,
 '44178808375.1002': 917,
 '44179777447.1021': 4139,
 '44180243322.1002': 894,
 '44182503906.100494': 3394,
 '44183175419.100494': 511,
 '44183473078.1021': 4198,
 '44183529577.1002': 4551,
 '44184723368.1002': 2421,
 '44184773625.51709': 4646,
 '44186077677.100494': 521,
 '44190241314.1059': 4253,
 '44190319972.100494': 984,
 '44190531087.1021': 4287,
 '44190825878.1018': 2216,
 '44194600275.1002': 5011,
 '44196690789.100494': 600,
 '44197454409.108894': 4758,
 '44199870198.100494': 4349,
 '44202123780.1091': 2970,
 '44204502894.100494': 4963,
 '44205582257.100494': 4554,
 '44209670874.1018': 1594,
 '44210415433.51674': 2486,
 '44211992264.996544': 3899,
 '44212846149.1098': 2089,
 '44215691646.100494': 429,
 '44223267078.1018': 1840,
 '44224856005.1021': 3643,
 '44226301833.996544': 631,
 '44233615425.1018': 1413,
 '44233685182.1021': 4019,
 '44233882952.100494': 4031,
 '44240566500.100494': 557,
 '44241875164.108894': 1441,
 '44241888130.100494': 1392,
 '44242118804.1021': 4695,
 '44242718686.36231': 3470,
 '44243093919.1021': 3623,
 '44244362736.1018': 97,
 '44247106763.1021': 3901,
 '44247830239.52815': 3450,
 '44248035238.1059': 5069,
 '44249710595.1021': 4280,
 '44255813117.100494': 1172,
 '44256248058.100494': 322,
 '44257692943.1036': 4817,
 '44258590701.1002': 4221,
 '44259768406.1021': 4242,
 '44261205572.1021': 3254,
 '44261250843.1093': 2492,
 '45001059242.1002': 3736,
 '45001979908.100494': 4078,
 '45002548508.100494': 2953,
 '45004984502.100494': 338,
 '45005344228.100494': 2852,
 '45005356382.1492': 3262,
 '45005660674.1021': 4438,
 '4500708141.1097': 2551,
 '45009662806.100494': 4146,
 '45014609566.100494': 3083,
 '45015459539.108894': 3506,

In [30]:
cursor.execute("SELECT nombre,feature_id FROM feature_catalog")

In [31]:
feat_map = { name: fid for name, fid in cursor.fetchall() }

In [32]:
# catálogo de features
feat_map

{'acepta_mascotas': 20,
 'adaptado_pmreducida': 10,
 'aire_acondicionado': 11,
 'amueblado': 16,
 'armarios_empotrados': 21,
 'ascensor': 1,
 'balcón': 2,
 'calefacción': 3,
 'chimenea': 4,
 'cocina_equipada': 17,
 'exterior': 5,
 'garaje': 6,
 'gasto_comunidad_eur': 19,
 'gastos_comunidad_eur': 22,
 'jardín': 9,
 'orientacion_list': 18,
 'piscina': 7,
 'puerta_blindada': 12,
 'sistema_seguridad': 14,
 'terraza': 15,
 'trastero': 8,
 'vidrios_dobles': 13}

## Localizar URLs nuevas, existentes y eliminadas

In [33]:
set_new = set(df_all['url'])
set_new

{'https://www.pisos.com/comprar/casa-moncloa_aravaca_el_plantio-50083150932_101800/',
 'https://www.pisos.com/alquilar/apartamento-puerta_del_angel-54220439892_101800/',
 'https://www.pisos.com/comprar/piso-costillares28033-53355745514_109300/',
 'https://www.pisos.com/alquilar/piso-salamanca_castellana28006-54175561100_100500/',
 'https://www.pisos.com/comprar/piso-ciudad_lineal_quintana-54252301351_100500/',
 'https://www.pisos.com/alquilar/piso-centro_palacio28005-55059610751_104700/',
 'https://www.pisos.com/comprar/piso-puente_de_vallecas_portazgo28038-55095268686_100200/',
 'https://www.pisos.com/alquilar/apartamento-centro_embajadores_lavapies28012-55014614169_101800/',
 'https://www.pisos.com/comprar/apartamento-chamartin_el_viso28006-52532486969_101800/',
 'https://www.pisos.com/alquilar/piso-chamberi_arapiles28015-42522425348_100500/',
 'https://www.pisos.com/comprar/atico-rios_rosas28003-49257554351_101800/',
 'https://www.pisos.com/alquilar/piso-salamanca_castellana28006-54185383221_996542/',
 'https://www.pisos.com/comprar/piso-chamartin_el_viso28002-24178797472_996542/',
 'https://www.pisos.com/comprar/piso-puente_de_vallecas_san_diego28018-55005771026_100200/',
 'https://www.pisos.com/comprar/piso-lista_barrio28006-53345050413_100500/',
 'https://www.pisos.com/alquilar/piso-universidad_malasana-54227666686_106600/',
 'https://www.pisos.com/comprar/piso-recoletos28009-45922635651_524671/',
 'https://www.pisos.com/comprar/piso-centro_palacio28005-52527271657_102100/',
 'https://www.pisos.com/comprar/piso-villaverde_san_andres28021-37537974067_100200/',
 'https://www.pisos.com/alquilar/piso-la_moraleja_encinar_de_los_reyes28109-54251321942_102100/',
 'https://www.pisos.com/alquilar/piso-legazpi_barrio28045-55028007164_108900/',
 'https://www.pisos.com/alquilar/piso-zofio28026-54214393326_104700/',
 'https://www.pisos.com/comprar/piso-ventas28017-55058652990_100500/',
 'https://www.pisos.com/alquilar/apartamento-nueva_espana28046-54208903948_101800/',
 'https://www.pisos.com/alquilar/piso-centro_palacio28013-51757479206_102100/',
 'https://www.pisos.com/comprar/apartamento-sol_barrio28012-38354406706_101800/',
 'https://www.pisos.com/comprar/piso-recoletos28001-54167193248_100500/',
 'https://www.pisos.com/comprar/atico-chamartin_prosperidad28002-50034202224_100500/',
 'https://www.pisos.com/comprar/piso-valdeacederas28039-53385634723_521737/',
 'https://www.pisos.com/comprar/piso-centro_palacio28005-48394768291_106700/',
 'https://www.pisos.com/comprar/atico-centro_palacio28013-38402321155_101800/',
 'https://www.pisos.com/comprar/piso-sol_barrio28013-52567923633_109300/',
 'https://www.pisos.com/comprar/apartamento-lista_barrio28006-55037252315_101800/',
 'https://www.pisos.com/alquilar/piso-justicia_chueca28004-24254231384_996542/',
 'https://www.pisos.com/comprar/piso-palomeras_bajas28018-49232196713_100200/',
 'https://www.pisos.com/comprar/piso-lista_barrio28006-50926595910_100500/',
 'https://www.pisos.com/comprar/casa_pareada-penagrande28035-53391833090_101800/',
 'https://www.pisos.com/comprar/piso-fuente_del_berro28028-55004644193_100200/',
 'https://www.pisos.com/comprar/atico-san_blas_salvador28027-52552431513_100500/',
 'https://www.pisos.com/comprar/piso-moncloa_aravaca_aravaca28023-4696645935_109700/',
 'https://www.pisos.com/comprar/piso-palomeras_sureste28031-53368241646_100500/',
 'https://www.pisos.com/alquilar/piso-castilla28036-53383736142_100500/',
 'https://www.pisos.com/alquilar/piso-salamanca_castellana28006-54235652798_108900/',
 'https://www.pisos.com/comprar/piso-chamartin_prosperidad28002-53374250111_100200/',
 'https://www.pisos.com/alquilar/piso-centro_palacio28013-51698164571_102100/',
 'https://www.pisos.com/comprar/piso-fontarron-55040522074_100200/',
 'https://www.pisos.com/alquilar/apartamento-almendrales28026-52546983302_109800/',
 'https://www.pisos.com/comprar/piso-casco_historico_de_vallecas28031-51743566916_105100/',
 'https://www.pisos.com/comprar/piso-barrio_de_salamanca_lista28006-53384415350_100500/',
 'https://www.pisos.com/alquilar/estudio-centro_palacio28005-55015610197_104700/',
 'https://www.pisos.com/alquilar/piso-goya28001-55039770885_109300/',
 'https://www.pisos.com/alquilar/piso-chamartin_prosperidad28002-55089856482_100500/',
 'https://www.pisos.com/comprar/piso-rejas28022-55068058545_100500/',
 'https://www.pisos.com/comprar/piso-chamberi_arapiles28015-55084241715_521707/',
 'https://www.pisos.com/comprar/chalet_adosado-nueva_espana28036-945856909447899_109700/',
 'https://www.pisos.com/comprar/piso-barrio_de_salamanca_castellana28006-51696060226_109300/',
 'https://www.pisos.com/comprar/piso-lista_barrio28006-54237852162_100500/',
 'https://www.pisos.com/comprar/apartamento-sol_barrio28012-55020721404_101800/',
 'https://www.pisos.com/comprar/apartamento-guindalera28028-50009280266_101800/',
 'https://www.pisos.com/comprar/piso-chamartin_prosperidad28043-41731912436_102100/',
 'https://www.pisos.com/comprar/piso-justicia_chueca28001-52505072844_102100/',
 'https://www.pisos.com/comprar/piso-justicia_chueca28004-49223942295_100500/',
 'https://www.pisos.com/alquilar/apartamento-bellas_vistas28039-52509880125_101800/',
 'https://www.pisos.com/alquilar/piso-gaztambide28015-54197112228_998787/',
 'https://www.pisos.com/alquilar/piso-recoletos28001-55072252295_100500/',
 'https://www.pisos.com/comprar/piso-casa_de_campo28008-55047902221_100500/',
 'https://www.pisos.com/comprar/piso-centro_embajadores_lavapies28005-53414174310_101000/',
 'https://www.pisos.com/alquilar/piso-pilar28029-55012742477_108900/',
 'https://www.pisos.com/comprar/piso-recoletos28001-53433311209_100500/',
 'https://www.pisos.com/comprar/piso-lista_barrio28001-53377709924_100500/',
 'https://www.pisos.com/comprar/apartamento-jeronimos28014-38373210531_101800/',
 'https://www.pisos.com/alquilar/apartamento-chamberi_arapiles28015-55060331777_101800/',
 'https://www.pisos.com/comprar/duplex-ciudad_lineal_colina28043-50016077616_101800/',
 'https://www.pisos.com/comprar/piso-los_berrocales_los_ahijones28031-5539512114_109700/',
 'https://www.pisos.com/comprar/piso-ensanche_de_vallecas_valdecarros28051-54248158558_100500/',
 'https://www.pisos.com/alquilar/piso-chamberi_arapiles28015-54199973226_108900/',
 'https://www.pisos.com/comprar/piso-palomeras_sureste28018-54242837550_100200/',
 'https://www.pisos.com/alquilar/piso-chamartin_hispanoamerica28016-53416155707_108900/',
 'https://www.pisos.com/comprar/piso-chamartin_el_viso28002-54235721567_100500/',
 'https://www.pisos.com/alquilar/estudio-chamartin_hispanoamerica28016-43348913744_996542/',
 'https://www.pisos.com/alquilar/piso-universidad_malasana28004-55073863077_100500/',
 'https://www.pisos.com/comprar/piso-san_blas_canillejas28022-55067954867_100500/',
 'https://www.pisos.com/comprar/piso-centro_embajadores_lavapies28012-48420384297_101800/',
 'https://www.pisos.com/comprar/piso-palos_de_moguer28045-54236417319_100500/',
 'https://www.pisos.com/comprar/piso-jeronimos28014-48403298558_149200/',
 'https://www.pisos.com/alquilar/piso-moncloa_aravaca_aravaca28023-55090523474_100500/',
 'https://www.pisos.com/alquilar/piso-salamanca_castellana28006-55022995313_108900/',
 'https://www.pisos.com/comprar/piso-salamanca_castellana28006-48423651125_100500/',
 'https://www.pisos.com/comprar/piso-puerta_del_angel-55011467458_100200/',
 'https://www.pisos.com/comprar/piso-cortes_huertas28014-55070501998_518589/',
 'https://www.pisos.com/alquilar/piso-numancia28038-54243510241_100500/',
 'https://www.pisos.com/comprar/piso-universidad_malasana28015-47514945452_100500/',
 'https://www.pisos.com/comprar/atico-virgen_del_cortijo_manoteras28050-53360006830_101800/',
 'https://www.pisos.com/comprar/chalet_pareado-casa_de_campo28011-54212538005_100900/',
 'https://www.pisos.com/comprar/piso-universidad_malasana28015-54182279694_102100/',
 'https://www.pisos.com/comprar/apartamento-centro_embajadores_lavapies28012-54214885027_101800/',
 'https://www.pisos.com/alquilar/piso-goya28001-42522444122_100500/',
 'https://www.pisos.com/comprar/piso-rejas28022-55012610490_100500/',
 'https://www.pisos.com/alquilar/apartamento-centro_palacio28013-50835038645_101800/',
 'https://www.pisos.com/comprar/piso-costillares28033-53378808786_108900/',
 'https://www.pisos.com/alquilar/chalet_adosado-la_moraleja_distrito28109-41750538995_179400/',
 'https://www.pisos.com/alquilar/piso-ciudad_universitaria28035-54255954652_108900/',
 'https://www.pisos.com/alquilar/chalet-moncloa_aravaca_aravaca28023-945856909558165_109700/',
 'https://www.pisos.com/alquilar/piso-chamberi_arapiles28015-52537066986_100200/',
 'https://www.pisos.com/alquilar/apartamento-centro_palacio28013-54171872790_101800/',
 'https://www.pisos.com/comprar/piso-orcasitas-38406785087_100500/',
 'https://www.pisos.com/comprar/piso-lucero28011-52579361723_529680/',
 'https://www.pisos.com/comprar/piso-centro_palacio28005-48398668929_106700/',
 'https://www.pisos.com/comprar/casa_pareada-fuencarral_el_pardo_valverde28034-54169001961_100200/',
 'https://www.pisos.com/alquilar/piso-universidad_malasana28004-42597500540_100500/',
 'https://www.pisos.com/comprar/piso-mirasierra_arroyo_del_fresno28035-53412179698_100200/',
 'https://www.pisos.com/alquilar/piso-centro_embajadores_lavapies28012-54189350232_104700/',
 'https://www.pisos.com/alquilar/atico-recoletos28001-53358152643_528426/',
 'https://www.pisos.com/comprar/piso-vicalvaro_ambroz28032-55099518071_994867/',
 'https://www.pisos.com/comprar/piso-san_fermin28041-55092863324_100200/',
 'https://www.pisos.com/comprar/piso-lista_barrio28006-50901755845_100500/',
 'https://www.pisos.com/alquilar/apartamento-salamanca_castellana28006-55002769795_101800/',
 'https://www.pisos.com/comprar/piso-san_blas_hellin28037-55038261473_100500/',
 'https://www.pisos.com/comprar/piso-guindalera28028-53411285628_102100/',
 'https://www.pisos.com/alquilar/piso-chamartin_hispanoamerica28036-55026252793_100500/',
 'https://www.pisos.com/comprar/duplex-rio_rosas28003-55098432586_520200/',
 'https://www.pisos.com/alquilar/piso-trafalgar28010-55081191769_100500/',
 'https://www.pisos.com/alquilar/piso-universidad_malasana28015-55036442564_100500/',
 'https://www.pisos.com/alquilar/chalet_pareado-la_moraleja_encinar_de_los_reyes-904123466_179400/',
 'https://www.pisos.com/comprar/apartamento-chamartin_el_viso28006-52581779550_101800/',
 'https://www.pisos.com/comprar/piso-retiro_pacifico-55056560939_106600/',
 'https://www.pisos.com/comprar/chalet-moncloa_aravaca_aravaca28023-51754380252_102100/',
 'https://www.pisos.com/comprar/piso-cortes_huertas28014-52551672840_100200/',
 'https://www.pisos.com/comprar/piso-universidad_malasana28004-52517149541_100500/',
 'https://www.pisos.com/alquilar/apartamento-centro_palacio28013-50873091515_101800/',
 'https://www.pisos.com/comprar/chalet-fuencarral_el_pardo_el_pardo28035-52518659838_102100/',
 'https://www.pisos.com/comprar/piso-recoletos28009-53421246932_108900/',
 'https://www.pisos.com/alquilar/piso-trafalgar28015-53338030276_108900/',
 'https://www.pisos.com/comprar/piso-trafalgar28010-54256912818_102100/',
 'https://www.pisos.com/comprar/piso-goya28001-51705308417_108900/',
 'https://www.pisos.com/comprar/piso-penagrande28035-53382818159_100200/',
 'https://www.pisos.com/comprar/piso-universidad_malasana28004-55019440874_100500/',
 'https://www.pisos.com/alquilar/piso-villa_de_vallecas_santa_eugenia28031-55003272349_108900/',
 'https://www.pisos.com/alquilar/piso-goya28001-15062498673_100500/',
 'https://www.pisos.com/comprar/piso-chamberi_almagro28010-25843393551_100500/',
 'https://www.pisos.com/comprar/piso-ciudad_lineal_pueblo_nuevo28017-27563527218_100200/',
 'https://www.pisos.com/alquilar/atico-rio_rosas28003-54210357613_101800/',
 'https://www.pisos.com/comprar/piso-palos_de_moguer28045-55015526455_100200/',
 'https://www.pisos.com/comprar/piso-trafalgar28010-55057032429_108900/',
 'https://www.pisos.com/comprar/piso-goya28001-54188361932_109300/',
 'https://www.pisos.com/alquilar/apartamento-lista_barrio28006-55080453230_100500/',
 'https://www.pisos.com/alquilar/atico-justicia_chueca28004-42595356334_100500/',
 'https://www.pisos.com/alquilar/piso-salamanca_castellana28006-42586905446_100500/',
 'https://www.pisos.com/alquilar/piso-goya28001-54240710837_108900/',
 'https://www.pisos.com/alquilar/piso-nueva_espana28036-55042357356_518209/',
 'https://www.pisos.com/alquilar/apartamento-goya28009-54246787991_101800/',
 'https://www.pisos.com/comprar/piso-recoletos28009-49171110338_524228/',
 'https://www.pisos.com/alquilar/piso-chamberi_almagro28010-42590103160_100500/',
 'https://www.pisos.com/comprar/piso-goya28009-51704548171_100500/',
 'https://www.pisos.com/alquilar/piso-nueva_espana28016-55064772836_104700/',
 'https://www.pisos.com/alquilar/piso-ciudad_lineal_pueblo_nuevo28017-40864488327_100500/',
 'https://www.pisos.com/alquilar/apartamento-rio_rosas28003-54244924850_101800/',
 'https://www.pisos.com/comprar/apartamento-centro_palacio28005-50020226973_101800/',
 'https://www.pisos.com/alquilar/piso-goya28009-42596334141_100500/',
 'https://www.pisos.com/comprar/apartamento-goya28001-53342280851_101800/',
 'https://www.pisos.com/comprar/piso-goya28006-55048532884_102100/',
 'https://www.pisos.com/comprar/chalet-piovera28043-52590409675_109300/',
 'https://www.pisos.com/alquilar/piso-justicia_chueca28004-54244337317_101800/',
 'https://www.pisos.com/alquilar/piso-sol_barrio28012-49211439174_529055/',
 'https://www.pisos.com/alquilar/piso-centro_embajadores_lavapies28012-52512072291_104700/',
 'https://www.pisos.com/alquilar/piso-valdebernardo28032-55089177955_108900/',
 'https://www.pisos.com/alquilar/apartamento-chamartin_hispanoamerica28016-54240760109_101800/',
 'https://www.pisos.com/alquilar/piso-almendrales28026-53403733170_109800/',
 'https://www.pisos.com/alquilar/piso-recoletos28001-55060538884_100500/',
 'https://www.pisos.com/alquilar/piso-carabanchel_san_isidro28019-55060181616_108900/',
 'https://www.pisos.com/comprar/piso-chamberi_arapiles28015-55067060989_100500/',
 'https://www.pisos.com/comprar/piso-sol_barrio28012-45005356382_149200/',
 'https://www.pisos.com/alquilar/piso-hortaleza_canillas28043-54184679213_108900/',
 'https://www.pisos.com/alquilar/piso-universidad_malasana28015-5916835829_100500/',
 'https://www.pisos.com/comprar/piso-pilar28029-53416365864_100500/',
 'https://www.pisos.com/comprar/apartamento-nino_jesus28007-49203956546_101800/',
 'https://www.pisos.com/alquilar/piso-moncloa_aravaca_arguelles28015-47519628630_996542/',
 'https://www.pisos.com/comprar/piso-centro_palacio28013-53366854590_105100/',
 'https://www.pisos.com/comprar/piso-trafalgar28010-53391256646_108700/',
 'https://www.pisos.com/comprar/piso-salamanca_castellana28006-50056771112_108900/',
 'https://www.pisos.com/comprar/piso-centro_embajadores_lavapies28012-55048107254_523686/',
 'https://www.pisos.com/alquilar/piso-guindalera28028-49265477296_996542/',
 'https://www.pisos.com/comprar/piso-fontarron-50911949923_100500/',
 'https://www.pisos.com/alquilar/piso-ventas28017-55085123428_108900/',
 'https://www.pisos.com/alquilar/piso-acacias28005-54193989047_100200/',
 'https://www.pisos.com/alquilar/piso-ibiza28009-51745028768_996542/',
 'https://www.pisos.com/alquilar/piso-pinar_del_rey28033-55030209473_100500/',
 'https://www.pisos.com/comprar/piso-abrantes28025-53400085658_991741/',
 'https://www.pisos.com/comprar/chalet-fuentelarreina28035-39193142319_101800/',
 'https://www.pisos.com/comprar/atico-los_berrocales_los_ahijones28031-5594182652_109700/',
 'https://www.pisos.com/comprar/piso-abrantes28041-55012208416_102100/',
 'https://www.pisos.com/comprar/piso-ibiza28009-51700001026_102100/',
 'https://www.pisos.com/comprar/atico-retiro_estrella28007-54254464389_109300/',
 'https://www.pisos.com/comprar/piso-salamanca_castellana28006-45009662806_100500/',
 'https://www.pisos.com/alquilar/piso-chamartin_hispanoamerica28016-52553260005_100500/',
 'https://www.pisos.com/comprar/piso-san_blas_simancas28037-5294849153_109700/',
 'https://www.pisos.com/alquilar/atico-tetuan_almenara28029-55013224165_100500/',
 'https://www.pisos.com/comprar/piso-salamanca_castellana28006-53338300295_101800/',
 'https://www.pisos.com/alquilar/apartamento-recoletos28001-55003216779_101800/',
 'https://www.pisos.com/comprar/piso-universidad_malasana28015-55024403981_102100/',
 'https://www.pisos.com/comprar/piso-goya28009-52572555780_109300/',
 'https://www.pisos.com/comprar/piso-recoletos28001-54166880463_362300/',
 'https://www.pisos.com/alquilar/piso-sol_barrio28014-54196403358_528990/',
 'https://www.pisos.com/comprar/piso-goya28009-51764843159_109300/',
 'https://www.pisos.com/alquilar/piso-centro_palacio28013-43407418131_996542/',
 'https://www.pisos.com/comprar/apartamento-recoletos28001-54177619812_101800/',
 'https://www.pisos.com/alquilar/piso-el_soto_de_la_moraleja28109-55091429426_100500/',
 'https://www.pisos.com/comprar/piso-valdeacederas28029-54203694504_100200/',
 'https://www.pisos.com/comprar/piso-centro_palacio28005-48401338011_102100/',
 'https://www.pisos.com/comprar/atico-justicia_chueca28004-54198475293_100500/',
 'https://www.pisos.com/comprar/apartamento-ibiza28009-55029568491_101800/',
 'https://www.pisos.com/comprar/piso-centro_palacio28013-53374495099_514774/',
 'https://www.pisos.com/comprar/piso-salamanca_castellana28006-37563341116_996542/',
 'https://www.pisos.com/alquilar/piso-retiro_pacifico28007-55098102532_108900/',
 'https://www.pisos.com/comprar/piso-moscardo28026-53409766277_100200/',
 'https://www.pisos.com/comprar/piso-san_blas_canillejas28022-54225647556_100500/',
 'https://www.pisos.com/comprar/piso-chamartin_hispanoamerica28016-55072016504_100200/',
 'https://www.pisos.com/comprar/piso-chamberi_arapiles28015-48362845152_100500/',
 'https://www.pisos.com/comprar/piso-acacias28005-53388277566_100500/',
 'https://www.pisos.com/alquilar/piso-castilla28046-53391655654_100500/',
 'https://www.pisos.com/comprar/piso-lista_barrio28006-53374796955_108900/',
 'https://www.pisos.com/alquilar/apartamento-cortes_huertas28014-55062229169_100900/',
 'https://www.pisos.com/alquilar/piso-centro_embajadores_lavapies28012-52561037752_108900/',
 'https://www.pisos.com/alquilar/piso-universidad_malasana28004-49254676481_520252/',
 'https://www.pisos.com/comprar/piso-rejas28022-53431757747_104700/',
 'https://www.pisos.com/alquilar/apartamento-chamberi_almagro28010-55099372914_108900/',
 'https://www.pisos.com/alquilar/estudio-centro_embajadores_lavapies28012-52529723435_104700/',
 'https://www.pisos.com/comprar/piso-centro_embajadores_lavapies28012-54226422963_102100/',
 'https://www.pisos.com/alquilar/estudio-chamberi_vallehermoso28003-55021733561_108900/',
 'https://www.pisos.com/comprar/apartamento-rios_rosas28003-51669964838_101800/',
 'https://www.pisos.com/alquilar/piso-moncloa_aravaca_arguelles28008-54227227184_520252/',
 'https://www.pisos.com/alquilar/piso-pilar28029-54176326656_108900/',
 'https://www.pisos.com/comprar/piso-pilar28029-53398625575_100200/',
 'https://www.pisos.com/alquilar/piso-chamartin_prosperidad28002-54213420906_106000/',
 'https://www.pisos.com/alquilar/estudio-universidad_malasana28004-54260994956_101800/',
 'https://www.pisos.com/comprar/piso-centro_embajadores_lavapies28012-52518286430_109300/',
 'https://www.pisos.com/comprar/piso-universidad_malasana28004-5015113295_101800/',
 'https://www.pisos.com/alquilar/piso-guindalera28028-54167070622_106000/',
 'https://www.pisos.com/alquilar/piso-rio_rosas28003-42531953958_100500/',
 'https://www.pisos.com/comprar/piso-castilla28034-41712723185_102100/',
 'https://www.pisos.com/comprar/piso-timon28042-53428921125_100200/',
 'https://www.pisos.com/alquilar/apartamento-atocha28045-54178707073_101800/',
 'https://www.pisos.com/comprar/piso-puerta_del_angel-55056380281_109100/',
 'https://www.pisos.com/alquilar/estudio-ciudad_lineal_quintana-38401942335_527206/',

In [34]:
set_old = set(map_list.keys())
set_old

{'https://www.pisos.com/alquilar/apartamento-puerta_del_angel-54220439892_101800/',
 'https://www.pisos.com/comprar/piso-costillares28033-53355745514_109300/',
 'https://www.pisos.com/alquilar/piso-salamanca_castellana28006-54175561100_100500/',
 'https://www.pisos.com/alquilar/apartamento-san_blas_salvador28027-53337746717_101800/',
 'https://www.pisos.com/comprar/piso-centro_embajadores_lavapies28012-54196603247_108500/',
 'https://www.pisos.com/comprar/atico-rios_rosas28003-49257554351_101800/',
 'https://www.pisos.com/alquilar/piso-los_berrocales_los_ahijones28031-54263732985_108900/',
 'https://www.pisos.com/alquilar/piso-salamanca_castellana28006-54185383221_996542/',
 'https://www.pisos.com/comprar/piso-chamartin_el_viso28002-24178797472_996542/',
 'https://www.pisos.com/comprar/piso-lista_barrio28006-53345050413_100500/',
 'https://www.pisos.com/comprar/piso-cortes_huertas28014-53406447604_108500/',
 'https://www.pisos.com/comprar/piso-recoletos28009-45922635651_524671/',
 'https://www.pisos.com/alquilar/piso-imperial28019-51691898221_102100/',
 'https://www.pisos.com/comprar/piso-centro_palacio28005-52527271657_102100/',
 'https://www.pisos.com/comprar/piso-villaverde_san_andres28021-37537974067_100200/',
 'https://www.pisos.com/comprar/piso-casco_historico_de_barajas-54245434891_528332/',
 'https://www.pisos.com/alquilar/piso-zofio28026-54214393326_104700/',
 'https://www.pisos.com/comprar/piso-orcasur28041-52575331099_100500/',
 'https://www.pisos.com/comprar/casa-san_blas_simancas28037-54187443772_520499/',
 'https://www.pisos.com/comprar/piso-pilar28029-52532566309_100200/',
 'https://www.pisos.com/alquilar/piso-centro_palacio28013-51757479206_102100/',
 'https://www.pisos.com/comprar/piso-justicia_chueca28004-46694875680_100500/',
 'https://www.pisos.com/comprar/atico-chamartin_prosperidad28002-50034202224_100500/',
 'https://www.pisos.com/comprar/piso-valdeacederas28039-53385634723_521737/',
 'https://www.pisos.com/comprar/piso-centro_palacio28005-48394768291_106700/',
 'https://www.pisos.com/comprar/piso-sol_barrio28013-52567923633_109300/',
 'https://www.pisos.com/alquilar/piso-justicia_chueca28004-24254231384_996542/',
 'https://www.pisos.com/comprar/piso-palomeras_bajas28018-49232196713_100200/',
 'https://www.pisos.com/comprar/casa_pareada-penagrande28035-53391833090_101800/',
 'https://www.pisos.com/comprar/piso-moncloa_aravaca_aravaca28023-4696645935_109700/',
 'https://www.pisos.com/comprar/atico-san_blas_salvador28027-52552431513_100500/',
 'https://www.pisos.com/comprar/piso-palomeras_sureste28031-53368241646_100500/',
 'https://www.pisos.com/alquilar/piso-castilla28036-53383736142_100500/',
 'https://www.pisos.com/alquilar/piso-salamanca_castellana28006-54235652798_108900/',
 'https://www.pisos.com/alquilar/piso-barrio_de_salamanca_castellana28006-52519149286_108900/',
 'https://www.pisos.com/comprar/piso-chamartin_prosperidad28002-53374250111_100200/',
 'https://www.pisos.com/alquilar/piso-centro_palacio28013-51698164571_102100/',
 'https://www.pisos.com/alquilar/apartamento-almendrales28026-52546983302_109800/',
 'https://www.pisos.com/comprar/piso-casco_historico_de_vallecas28031-51743566916_105100/',
 'https://www.pisos.com/comprar/piso-barrio_de_salamanca_lista28006-53384415350_100500/',
 'https://www.pisos.com/comprar/chalet_adosado-nueva_espana28036-945856909447899_109700/',
 'https://www.pisos.com/comprar/piso-recoletos28001-53363934828_108900/',
 'https://www.pisos.com/comprar/piso-barrio_de_salamanca_castellana28006-51696060226_109300/',
 'https://www.pisos.com/alquilar/piso-hortaleza_canillas28043-54196913478_996542/',
 'https://www.pisos.com/comprar/piso-lista_barrio28006-54237852162_100500/',
 'https://www.pisos.com/comprar/piso-penagrande28035-49170443855_100200/',
 'https://www.pisos.com/alquilar/piso-rios_rosas28003-42594169395_100500/',
 'https://www.pisos.com/alquilar/apartamento-concepcion28027-53369050952_101800/',
 'https://www.pisos.com/comprar/piso-chamartin_prosperidad28043-41731912436_102100/',
 'https://www.pisos.com/alquilar/piso-chamberi_almagro28010-42596572500_100500/',
 'https://www.pisos.com/comprar/piso-justicia_chueca28001-52505072844_102100/',
 'https://www.pisos.com/alquilar/piso-rio_rosas28003-53366218558_108900/',
 'https://www.pisos.com/comprar/piso-justicia_chueca28004-49223942295_100500/',
 'https://www.pisos.com/alquilar/apartamento-bellas_vistas28039-52509880125_101800/',
 'https://www.pisos.com/alquilar/piso-gaztambide28015-54197112228_998787/',
 'https://www.pisos.com/comprar/piso-universidad_malasana28015-48359925980_102100/',
 'https://www.pisos.com/alquilar/piso-montecarmelo28050-53360934566_102100/',
 'https://www.pisos.com/comprar/piso-centro_embajadores_lavapies28005-53414174310_101000/',
 'https://www.pisos.com/comprar/piso-recoletos28001-53433311209_100500/',
 'https://www.pisos.com/alquilar/apartamento-goya28001-54229529044_101800/',
 'https://www.pisos.com/comprar/piso-lista_barrio28001-53377709924_100500/',
 'https://www.pisos.com/comprar/piso-retiro_pacifico28007-54265767350_100500/',
 'https://www.pisos.com/comprar/piso-ensanche_de_vallecas_valdecarros28051-54248158558_100500/',
 'https://www.pisos.com/alquilar/piso-chamberi_arapiles28015-54199973226_108900/',
 'https://www.pisos.com/comprar/estudio-piovera28043-54182667663_109800/',
 'https://www.pisos.com/alquilar/piso-trafalgar28010-54207744004_100500/',
 'https://www.pisos.com/comprar/piso-palomeras_sureste28018-54242837550_100200/',
 'https://www.pisos.com/alquilar/piso-fuente_del_berro28028-54210966519_108900/',
 'https://www.pisos.com/alquilar/piso-chamartin_hispanoamerica28016-53416155707_108900/',
 'https://www.pisos.com/comprar/piso-chamartin_el_viso28002-54235721567_100500/',
 'https://www.pisos.com/alquilar/estudio-chamartin_hispanoamerica28016-43348913744_996542/',
 'https://www.pisos.com/comprar/piso-centro_embajadores_lavapies28012-48420384297_101800/',
 'https://www.pisos.com/alquilar/piso-salamanca_castellana28006-53425461171_100500/',
 'https://www.pisos.com/comprar/piso-palos_de_moguer28045-54236417319_100500/',
 'https://www.pisos.com/comprar/piso-jeronimos28014-48403298558_149200/',
 'https://www.pisos.com/comprar/piso-salamanca_castellana28006-48423651125_100500/',
 'https://www.pisos.com/comprar/piso-alameda_de_osuna_barrio-52585131250_105100/',
 'https://www.pisos.com/alquilar/piso-numancia28038-54243510241_100500/',
 'https://www.pisos.com/comprar/piso-universidad_malasana28015-47514945452_100500/',
 'https://www.pisos.com/alquilar/piso-san_blas_simancas28037-54231127069_109800/',
 'https://www.pisos.com/comprar/piso-imperial28005-53399776882_100500/',
 'https://www.pisos.com/alquilar/piso-puente_de_vallecas_san_diego28053-53344007323_100500/',
 'https://www.pisos.com/comprar/piso-universidad_malasana28015-54182279694_102100/',
 'https://www.pisos.com/comprar/piso-palomeras_bajas28018-52501248309_103800/',
 'https://www.pisos.com/alquilar/apartamento-centro_palacio28013-50835038645_101800/',
 'https://www.pisos.com/comprar/piso-costillares28033-53378808786_108900/',
 'https://www.pisos.com/alquilar/piso-justicia_chueca28004-52546728652_100500/',
 'https://www.pisos.com/alquilar/chalet-moncloa_aravaca_aravaca28023-945856909558165_109700/',
 'https://www.pisos.com/alquilar/piso-chamberi_arapiles28015-52537066986_100200/',
 'https://www.pisos.com/alquilar/estudio-castillejos28020-54177834965_100500/',
 'https://www.pisos.com/alquilar/apartamento-centro_palacio28013-54171872790_101800/',
 'https://www.pisos.com/comprar/piso-orcasitas-38406785087_100500/',
 'https://www.pisos.com/comprar/piso-lucero28011-52579361723_529680/',
 'https://www.pisos.com/alquilar/piso-acacias28005-53418168606_100500/',
 'https://www.pisos.com/comprar/piso-centro_palacio28005-48398668929_106700/',
 'https://www.pisos.com/comprar/casa_pareada-fuencarral_el_pardo_valverde28034-54169001961_100200/',
 'https://www.pisos.com/comprar/piso-ciudad_lineal_quintana-50893554780_100200/',
 'https://www.pisos.com/alquilar/apartamento-chamartin_hispanoamerica28016-52542532287_101800/',
 'https://www.pisos.com/alquilar/piso-universidad_malasana28004-42597500540_100500/',
 'https://www.pisos.com/comprar/piso-berruguete28039-54204263054_100200/',
 'https://www.pisos.com/comprar/piso-mirasierra_arroyo_del_fresno28035-53412179698_100200/',
 'https://www.pisos.com/alquilar/piso-centro_embajadores_lavapies28012-54189350232_104700/',
 'https://www.pisos.com/alquilar/piso-ventas28017-54227281078_108900/',
 'https://www.pisos.com/alquilar/atico-recoletos28001-53358152643_528426/',
 'https://www.pisos.com/comprar/piso-goya28001-54214850712_100500/',
 'https://www.pisos.com/comprar/piso-lista_barrio28006-50901755845_100500/',
 'https://www.pisos.com/comprar/piso-guindalera28028-53411285628_102100/',
 'https://www.pisos.com/comprar/loft-pinar_del_rey28033-53429917829_529625/',
 'https://www.pisos.com/comprar/piso-sol_barrio28013-53432052383_100500/',
 'https://www.pisos.com/alquilar/piso-tetuan_almenara28046-54259348203_108900/',
 'https://www.pisos.com/alquilar/apartamento-carabanchel_comillas28019-50078353350_100500/',
 'https://www.pisos.com/alquilar/piso-puente_de_vallecas_san_diego28018-21711813995_100500/',
 'https://www.pisos.com/comprar/piso-sol_barrio28013-50895699546_100500/',
 'https://www.pisos.com/comprar/piso-chamberi_almagro28010-51673642102_108500/',
 'https://www.pisos.com/comprar/chalet-moncloa_aravaca_aravaca28023-51754380252_102100/',
 'https://www.pisos.com/comprar/piso-cortes_huertas28014-52551672840_100200/',
 'https://www.pisos.com/comprar/piso-universidad_malasana28004-52517149541_100500/',
 'https://www.pisos.com/alquilar/apartamento-centro_palacio28013-50873091515_101800/',
 'https://www.pisos.com/comprar/chalet-fuencarral_el_pardo_el_pardo28035-52518659838_102100/',
 'https://www.pisos.com/alquilar/piso-trafalgar28015-53338030276_108900/',
 'https://www.pisos.com/comprar/piso-trafalgar28010-54256912818_102100/',
 'https://www.pisos.com/comprar/piso-goya28001-51705308417_108900/',
 'https://www.pisos.com/comprar/piso-penagrande28035-53382818159_100200/',
 'https://www.pisos.com/comprar/piso-chamberi_almagro28010-25843393551_100500/',
 'https://www.pisos.com/comprar/piso-ciudad_lineal_pueblo_nuevo28017-27563527218_100200/',
 'https://www.pisos.com/alquilar/atico-rio_rosas28003-54210357613_101800/',
 'https://www.pisos.com/comprar/piso-ciudad_universitaria28040-54208654963_106000/',
 'https://www.pisos.com/comprar/piso-puerta_bonita-54245964998_106600/',
 'https://www.pisos.com/alquilar/atico-justicia_chueca28004-42595356334_100500/',
 'https://www.pisos.com/alquilar/piso-salamanca_castellana28006-42586905446_100500/',
 'https://www.pisos.com/alquilar/piso-goya28001-54240710837_108900/',
 'https://www.pisos.com/comprar/piso-recoletos28009-49171110338_524228/',
 'https://www.pisos.com/comprar/piso-goya28009-51704548171_100500/',
 'https://www.pisos.com/comprar/piso-valdeacederas28029-50931552331_100200/',
 'https://www.pisos.com/alquilar/apartamento-rio_rosas28003-54244924850_101800/',
 'https://www.pisos.com/alquilar/apartamento-centro_palacio28005-54264967818_101800/',
 'https://www.pisos.com/comprar/chalet-piovera28043-52590409675_109300/',
 'https://www.pisos.com/alquilar/piso-justicia_chueca28004-54244337317_101800/',
 'https://www.pisos.com/comprar/piso-ventas28017-54177771697_100500/',
 'https://www.pisos.com/alquilar/piso-sol_barrio28012-49211439174_529055/',
 'https://www.pisos.com/alquilar/piso-centro_embajadores_lavapies28012-52512072291_104700/',
 'https://www.pisos.com/alquilar/apartamento-chamartin_hispanoamerica28016-54240760109_101800/',
 'https://www.pisos.com/alquilar/piso-almendrales28026-53403733170_109800/',
 'https://www.pisos.com/alquilar/piso-chamberi_almagro-54168611758_106600/',
 'https://www.pisos.com/comprar/piso-lista_barrio28006-53423670044_108900/',
 'https://www.pisos.com/comprar/piso-sol_barrio28012-45005356382_149200/',
 'https://www.pisos.com/alquilar/piso-hortaleza_canillas28043-54184679213_108900/',
 'https://www.pisos.com/alquilar/piso-universidad_malasana28015-5916835829_100500/',
 'https://www.pisos.com/alquilar/piso-chamartin_hispanoamerica28016-49191656125_996542/',
 'https://www.pisos.com/comprar/piso-pilar28029-53416365864_100500/',
 'https://www.pisos.com/alquilar/piso-moncloa_aravaca_arguelles28015-47519628630_996542/',
 'https://www.pisos.com/comprar/piso-centro_palacio28013-53366854590_105100/',
 'https://www.pisos.com/comprar/piso-salamanca_castellana28006-50056771112_108900/',
 'https://www.pisos.com/alquilar/piso-cortes_huertas28014-54213010822_100500/',
 'https://www.pisos.com/alquilar/piso-guindalera28028-49265477296_996542/',
 'https://www.pisos.com/alquilar/apartamento-chamberi_vallehermoso28003-54234313638_101800/',
 'https://www.pisos.com/comprar/piso-fontarron-50911949923_100500/',
 'https://www.pisos.com/comprar/piso-recoletos28001-37541355595_100500/',
 'https://www.pisos.com/alquilar/piso-ibiza28009-51745028768_996542/',
 'https://www.pisos.com/comprar/piso-ventas28017-52588716110_100200/',
 'https://www.pisos.com/comprar/piso-trafalgar28010-54258689741_100500/',
 'https://www.pisos.com/comprar/piso-latina_aluche28047-53398546008_100200/',
 'https://www.pisos.com/comprar/piso-abrantes28025-53400085658_991741/',
 'https://www.pisos.com/comprar/chalet-fuentelarreina28035-39193142319_101800/',
 'https://www.pisos.com/comprar/piso-recoletos28009-53335915816_108900/',
 'https://www.pisos.com/comprar/piso-palomeras_bajas28018-52597863047_991741/',
 'https://www.pisos.com/alquilar/piso-puerta_del_angel-52534198400_108900/',
 'https://www.pisos.com/comprar/piso-ibiza28009-51700001026_102100/',
 'https://www.pisos.com/comprar/atico-retiro_estrella28007-54254464389_109300/',
 'https://www.pisos.com/comprar/piso-salamanca_castellana28006-45009662806_100500/',
 'https://www.pisos.com/alquilar/piso-justicia_chueca-54265057368_106600/',
 'https://www.pisos.com/alquilar/piso-chamartin_hispanoamerica28016-52553260005_100500/',
 'https://www.pisos.com/comprar/piso-san_blas_simancas28037-5294849153_109700/',
 'https://www.pisos.com/comprar/piso-salamanca_castellana28006-53338300295_101800/',
 'https://www.pisos.com/comprar/piso-goya28009-52572555780_109300/',
 'https://www.pisos.com/comprar/piso-recoletos28001-54166880463_362300/',
 'https://www.pisos.com/alquilar/piso-sol_barrio28014-54196403358_528990/',
 'https://www.pisos.com/comprar/piso-goya28009-51764843159_109300/',
 'https://www.pisos.com/alquilar/piso-centro_palacio28013-43407418131_996542/',
 'https://www.pisos.com/alquilar/piso-sanchinarro28050-45932641396_100500/',
 'https://www.pisos.com/alquilar/piso-nueva_espana28016-54187060207_100500/',
 'https://www.pisos.com/comprar/piso-valdeacederas28029-54203694504_100200/',
 'https://www.pisos.com/comprar/piso-centro_palacio28005-48401338011_102100/',
 'https://www.pisos.com/alquilar/piso-chamberi_arapiles28015-54227705166_108900/',
 'https://www.pisos.com/comprar/atico-justicia_chueca28004-54198475293_100500/',
 'https://www.pisos.com/comprar/piso-recoletos28001-44242718686_362300/',
 'https://www.pisos.com/comprar/piso-centro_palacio28013-53374495099_514774/',
 'https://www.pisos.com/comprar/piso-salamanca_castellana28006-37563341116_996542/',
 'https://www.pisos.com/comprar/atico-los_berrocales_los_ahijones28031-5450472061_109700/',
 'https://www.pisos.com/alquilar/piso-pilar28029-54199552503_101000/',
 'https://www.pisos.com/comprar/piso-moscardo28026-53409766277_100200/',
 'https://www.pisos.com/alquilar/piso-centro_embajadores_lavapies28012-54176452947_100200/',
 'https://www.pisos.com/comprar/piso-chamberi_arapiles28015-48362845152_100500/',
 'https://www.pisos.com/comprar/piso-san_blas_canillejas28022-54225647556_100500/',
 'https://www.pisos.com/comprar/piso-acacias28005-53388277566_100500/',
 'https://www.pisos.com/alquilar/piso-castilla28046-53391655654_100500/',
 'https://www.pisos.com/comprar/piso-lista_barrio28006-53374796955_108900/',
 'https://www.pisos.com/alquilar/piso-centro_embajadores_lavapies28012-52561037752_108900/',
 'https://www.pisos.com/alquilar/piso-universidad_malasana28004-49254676481_520252/',
 'https://www.pisos.com/comprar/piso-rejas28022-53431757747_104700/',
 'https://www.pisos.com/alquilar/estudio-centro_embajadores_lavapies28012-52529723435_104700/',
 'https://www.pisos.com/comprar/piso-centro_embajadores_lavapies28012-54226422963_102100/',
 'https://www.pisos.com/alquilar/piso-costillares28033-54208960743_100500/',
 'https://www.pisos.com/comprar/piso-abrantes28025-52589074998_101800/',
 'https://www.pisos.com/alquilar/piso-puerta_del_angel-54195192843_104700/',
 'https://www.pisos.com/alquilar/piso-moncloa_aravaca_arguelles28008-54227227184_520252/',
 'https://www.pisos.com/alquilar/piso-pilar28029-54176326656_108900/',
 'https://www.pisos.com/comprar/piso-pilar28029-53398625575_100200/',
 'https://www.pisos.com/comprar/piso-justicia_chueca28004-52530152095_523378/',
 'https://www.pisos.com/alquilar/piso-chamartin_prosperidad28002-54213420906_106000/',
 'https://www.pisos.com/alquilar/estudio-universidad_malasana28004-54260994956_101800/',
 'https://www.pisos.com/comprar/piso-centro_embajadores_lavapies28012-52518286430_109300/',
 'https://www.pisos.com/comprar/piso-universidad_malasana28004-5015113295_101800/',
 'https://www.pisos.com/comprar/atico-penagrande28035-52520286870_515487/',
 'https://www.pisos.com/alquilar/piso-guindalera28028-54167070622_106000/',
 'https://www.pisos.com/comprar/piso-fuencarral_el_pardo_valverde28034-54217371214_100200/',
 'https://www.pisos.com/alquilar/piso-rio_rosas28003-42531953958_100500/',
 'https://www.pisos.com/comprar/piso-castilla28034-41712723185_102100/',
 'https://www.pisos.com/comprar/piso-timon28042-53428921125_100200/',
 'https://www.pisos.com/alquilar/apartamento-atocha28045-54178707073_101800/',
 'https://www.pisos.com/alquilar/estudio-ciudad_lineal_quintana-38401942335_527206/',
 'https://www.pisos.com/comprar/piso-salamanca_castellana28006-48389101209_100500/',
 'https://www.pisos.com/alquilar/atico-justicia_chueca28004-25020522818_996542/',
 'https://www.pisos.com/alquilar/piso-chamberi_almagro28010-42537467599_100500/',
 'https://www.pisos.com/alquilar/apartamento-salamanca_castellana28006-53402649278_101800/',
 'https://www.pisos.com/comprar/piso-imperial28005-50879986225_523686/',
 'https://www.pisos.com/alquilar/piso-puente_de_vallecas_entrevias28053-54171173607_108900/',
 'https://www.pisos.com/alquilar/piso-centro_palacio28013-35043837312_100500/',
 'https://www.pisos.com/alquilar/piso-chamberi_almagro28010-42585822676_100500/',
 'https://www.pisos.com/alquilar/estudio-nueva_espana28036-54175210805_106000/',
 'https://www.pisos.com/comprar/piso-latina_aluche28024-54177290349_100500/',
 'https://www.pisos.com/alquilar/piso-fuencarral_el_pardo_las_tablas28050-54169252204_108900/',
 'https://www.pisos.com/comprar/piso-centro_palacio28013-44233685182_102100/',
 'https://www.pisos.com/alquilar/apartamento-chamberi_vallehermoso28003-51711044484_101800/',
 'https://www.pisos.com/comprar/piso-justicia_chueca28004-50088156223_100500/',
 'https://www.pisos.com/comprar/atico-chamberi_almagro28010-47579035964_101800/',
 'https://www.pisos.com/alquilar/apartamento-retiro_estrella28007-53334560143_101800/',
 'https://www.pisos.com/comprar/piso-centro_embajadores_lavapies28012-53334751912_100200/',
 'https://www.pisos.com/comprar/piso-villaverde_san_andres28021-53400891036_100200/',
 'https://www.pisos.com/comprar/piso-moncloa_aravaca_aravaca28023-4703036613_109700/',
 'https://www.pisos.com/comprar/piso-universidad_malasana28004-51742072143_100500/',
 'https://www.pisos.com/alquilar/piso-carabanchel_comillas28019-51685732146_108900/',
 'https://www.pisos.com/alquilar/duplex-valdeacederas28039-20057768451_100500/',
 'https://www.pisos.com/alquilar/apartamento-universidad_malasana28015-53343188944_101800/',
 'https://www.pisos.com/alquilar/piso-casa_de_campo28008-54182301712_108900/',

In [35]:
to_insert = set_new - set_old
to_insert

{'https://www.pisos.com/comprar/piso-centro_embajadores_lavapies28012-55051854816_102100/',
 'https://www.pisos.com/comprar/piso-villa_de_vallecas_santa_eugenia28031-53335763863_100500/',
 'https://www.pisos.com/comprar/casa-moncloa_aravaca_el_plantio-50083150932_101800/',
 'https://www.pisos.com/alquilar/piso-san_juan_bautista28043-55007672298_108900/',
 'https://www.pisos.com/comprar/apartamento-centro_embajadores_lavapies28012-54210082745_101800/',
 'https://www.pisos.com/alquilar/piso-acacias28005-55094963954_109800/',
 'https://www.pisos.com/alquilar/piso-cortes_huertas28014-55032429404_108500/',
 'https://www.pisos.com/alquilar/piso-chamberi_almagro28010-55019368437_100500/',
 'https://www.pisos.com/comprar/piso-ciudad_lineal_quintana-54252301351_100500/',
 'https://www.pisos.com/comprar/piso-atocha28007-55099931894_102100/',
 'https://www.pisos.com/alquilar/piso-centro_palacio28005-55059610751_104700/',
 'https://www.pisos.com/comprar/piso-puente_de_vallecas_portazgo28038-55095268686_100200/',
 'https://www.pisos.com/comprar/apartamento-valdemarin-55009002920_101800/',
 'https://www.pisos.com/alquilar/apartamento-centro_embajadores_lavapies28012-55014614169_101800/',
 'https://www.pisos.com/comprar/apartamento-salamanca_castellana28006-53363722172_101800/',
 'https://www.pisos.com/comprar/piso-chamberi_arapiles28015-55058096301_100200/',
 'https://www.pisos.com/comprar/apartamento-chamartin_el_viso28006-52532486969_101800/',
 'https://www.pisos.com/alquilar/piso-chamberi_arapiles28015-42522425348_100500/',
 'https://www.pisos.com/alquilar/piso-chamartin_prosperidad28002-55046344078_100500/',
 'https://www.pisos.com/comprar/piso-ciudad_lineal_san_pascual28027-54197998040_100200/',
 'https://www.pisos.com/comprar/piso-puente_de_vallecas_san_diego28018-55005771026_100200/',
 'https://www.pisos.com/alquilar/estudio-puerta_del_angel-52536607870_104700/',
 'https://www.pisos.com/comprar/apartamento-universidad_malasana28004-51717415753_101800/',
 'https://www.pisos.com/alquilar/piso-universidad_malasana-54227666686_106600/',
 'https://www.pisos.com/comprar/piso-ciudad_lineal_quintana-55028763995_100500/',
 'https://www.pisos.com/comprar/piso-palomeras_sureste28018-55069263297_100200/',
 'https://www.pisos.com/alquilar/piso-salamanca_castellana28006-55043101502_106000/',
 'https://www.pisos.com/alquilar/piso-la_moraleja_encinar_de_los_reyes28109-54251321942_102100/',
 'https://www.pisos.com/alquilar/piso-centro_palacio28005-55018636009_102100/',
 'https://www.pisos.com/comprar/piso-justicia_chueca28001-55066610668_102100/',
 'https://www.pisos.com/comprar/apartamento-nino_jesus28007-55001535048_101800/',
 'https://www.pisos.com/comprar/piso-chopera28045-55039330045_100200/',
 'https://www.pisos.com/comprar/piso-centro_palacio28005-55048858766_102100/',
 'https://www.pisos.com/alquilar/piso-legazpi_barrio28045-55028007164_108900/',
 'https://www.pisos.com/alquilar/piso-centro_palacio28013-55069478271_100500/',
 'https://www.pisos.com/comprar/apartamento-centro_palacio28005-49231067683_101800/',
 'https://www.pisos.com/comprar/piso-lucero28047-55086196742_994867/',
 'https://www.pisos.com/comprar/piso-ventas28017-55058652990_100500/',
 'https://www.pisos.com/alquilar/apartamento-nueva_espana28046-54208903948_101800/',
 'https://www.pisos.com/comprar/apartamento-sol_barrio28012-38354406706_101800/',
 'https://www.pisos.com/comprar/piso-goya28001-55038847210_100500/',
 'https://www.pisos.com/comprar/piso-recoletos28001-54167193248_100500/',
 'https://www.pisos.com/alquilar/piso-fuencarral_el_pardo_las_tablas28050-55034887012_109300/',
 'https://www.pisos.com/comprar/piso-carabanchel_san_isidro28019-55093881828_510380/',
 'https://www.pisos.com/comprar/piso-vinateros-54213087251_106000/',
 'https://www.pisos.com/alquilar/piso-carabanchel_san_isidro28019-54177107454_108900/',
 'https://www.pisos.com/comprar/atico-centro_palacio28013-38402321155_101800/',
 'https://www.pisos.com/comprar/apartamento-imperial28005-55007757683_101800/',
 'https://www.pisos.com/comprar/apartamento-lista_barrio28006-55037252315_101800/',
 'https://www.pisos.com/comprar/piso-ibiza28009-55076402855_510380/',
 'https://www.pisos.com/comprar/piso-salamanca_castellana28006-48380237065_108900/',
 'https://www.pisos.com/comprar/piso-lista_barrio28006-50926595910_100500/',
 'https://www.pisos.com/comprar/piso-moncloa_aravaca_arguelles28008-55037655658_100500/',
 'https://www.pisos.com/alquilar/piso-san_juan_bautista28043-55056744477_108900/',
 'https://www.pisos.com/alquilar/chalet-la_moraleja_encinar_de_los_reyes28109-54225808685_102100/',
 'https://www.pisos.com/comprar/piso-fuente_del_berro28028-55004644193_100200/',
 'https://www.pisos.com/alquilar/piso-lista_barrio28006-55037384847_108900/',
 'https://www.pisos.com/alquilar/estudio-zofio28026-52503473983_104700/',
 'https://www.pisos.com/comprar/piso-goya28009-54263818126_100500/',
 'https://www.pisos.com/comprar/apartamento-ibiza28009-54236793976_101800/',
 'https://www.pisos.com/alquilar/piso-goya28009-54193546779_108900/',
 'https://www.pisos.com/comprar/apartamento-chamberi_vallehermoso28003-55002499204_101800/',
 'https://www.pisos.com/comprar/atico-justicia_chueca28004-55060381943_149200/',
 'https://www.pisos.com/comprar/piso-fontarron-55040522074_100200/',
 'https://www.pisos.com/comprar/piso-corralejos28042-40929661796_103600/',
 'https://www.pisos.com/comprar/piso-carabanchel_san_isidro28019-55010499911_104700/',
 'https://www.pisos.com/alquilar/estudio-centro_palacio28005-55015610197_104700/',
 'https://www.pisos.com/alquilar/piso-goya28001-55039770885_109300/',
 'https://www.pisos.com/alquilar/estudio-centro_embajadores_lavapies28012-55093146239_100500/',
 'https://www.pisos.com/alquilar/piso-chamartin_prosperidad28002-55089856482_100500/',
 'https://www.pisos.com/comprar/piso-rejas28022-55068058545_100500/',
 'https://www.pisos.com/comprar/piso-guindalera28028-55003276537_100500/',
 'https://www.pisos.com/comprar/piso-salamanca_castellana28006-55054273212_520200/',
 'https://www.pisos.com/comprar/piso-chamberi_arapiles28015-55084241715_521707/',
 'https://www.pisos.com/comprar/atico-trafalgar28015-53389620042_101800/',
 'https://www.pisos.com/comprar/apartamento-sol_barrio28012-55020721404_101800/',
 'https://www.pisos.com/alquilar/piso-universidad_malasana28015-54182920824_104700/',
 'https://www.pisos.com/comprar/apartamento-goya28001-54193942465_101800/',
 'https://www.pisos.com/comprar/apartamento-guindalera28028-50009280266_101800/',
 'https://www.pisos.com/alquilar/piso-universidad_malasana-55062604687_106600/',
 'https://www.pisos.com/comprar/piso-retiro_estrella28007-43405510349_100200/',
 'https://www.pisos.com/alquilar/piso-palos_de_moguer28045-54233636851_104700/',
 'https://www.pisos.com/comprar/piso-hortaleza_canillas28043-53363491417_100200/',
 'https://www.pisos.com/comprar/apartamento-universidad_malasana28004-51712995456_101800/',
 'https://www.pisos.com/alquilar/piso-tetuan_cuatro_caminos28020-49183888742_529055/',
 'https://www.pisos.com/alquilar/atico-ensanche_de_vallecas_valdecarros28031-55086797845_100500/',
 'https://www.pisos.com/alquilar/piso-recoletos28001-54192559954_100500/',
 'https://www.pisos.com/comprar/piso-villaverde_san_cristobal-55033841613_100200/',
 'https://www.pisos.com/comprar/piso-universidad_malasana28004-54194394715_100500/',
 'https://www.pisos.com/alquilar/piso-recoletos28001-55072252295_100500/',
 'https://www.pisos.com/alquilar/piso-rio_rosas28003-55013574885_100500/',
 'https://www.pisos.com/comprar/piso-casa_de_campo28008-55047902221_100500/',
 'https://www.pisos.com/alquilar/estudio-centro_embajadores_lavapies28012-54200801335_100500/',
 'https://www.pisos.com/comprar/piso-villa_de_vallecas_santa_eugenia28031-55063492461_100500/',
 'https://www.pisos.com/comprar/piso-san_blas_canillejas28022-55078382013_108500/',
 'https://www.pisos.com/comprar/piso-goya28006-55007833653_100500/',
 'https://www.pisos.com/comprar/piso-centro_palacio28005-55069811104_102100/',
 'https://www.pisos.com/alquilar/piso-pilar28029-55012742477_108900/',
 'https://www.pisos.com/alquilar/piso-acacias28005-55037553162_108900/',
 'https://www.pisos.com/comprar/finca_rustica-casco_historico_de_vallecas28031-55047352317_106600/',
 'https://www.pisos.com/alquilar/piso-numancia28038-47504235226_100500/',
 'https://www.pisos.com/comprar/piso-goya28006-50918670605_100500/',
 'https://www.pisos.com/alquilar/piso-chamartin_hispanoamerica28036-55077556944_100500/',
 'https://www.pisos.com/alquilar/piso-valdezarza28039-55077011740_100500/',
 'https://www.pisos.com/alquilar/piso-universidad_malasana28015-52531563378_108900/',
 'https://www.pisos.com/comprar/apartamento-jeronimos28014-38373210531_101800/',
 'https://www.pisos.com/alquilar/apartamento-chamberi_arapiles28015-55060331777_101800/',
 'https://www.pisos.com/comprar/piso-fuente_del_berro28028-55063858430_100500/',
 'https://www.pisos.com/alquilar/apartamento-goya28006-55097532868_101800/',
 'https://www.pisos.com/comprar/duplex-ciudad_lineal_colina28043-50016077616_101800/',
 'https://www.pisos.com/comprar/piso-los_berrocales_los_ahijones28031-5539512114_109700/',
 'https://www.pisos.com/comprar/piso-chamartin_el_viso28016-55038627269_102100/',
 'https://www.pisos.com/alquilar/piso-puerta_bonita28025-32548859607_100500/',
 'https://www.pisos.com/alquilar/estudio-centro_embajadores_lavapies28005-15851443163_100500/',
 'https://www.pisos.com/alquilar/piso-usera_pradolongo28026-35874957598_100500/',
 'https://www.pisos.com/comprar/piso-gaztambide28015-54216241261_105100/',
 'https://www.pisos.com/comprar/piso-ciudad_lineal_pueblo_nuevo28017-54214860829_100200/',
 'https://www.pisos.com/comprar/piso-lista_barrio28006-55065438230_100500/',
 'https://www.pisos.com/alquilar/piso-universidad_malasana28004-55073863077_100500/',
 'https://www.pisos.com/comprar/piso-san_blas_canillejas28022-55067954867_100500/',
 'https://www.pisos.com/comprar/piso-san_blas_simancas28037-54225089155_102200/',
 'https://www.pisos.com/alquilar/piso-salamanca_castellana28006-55022995313_108900/',
 'https://www.pisos.com/alquilar/piso-moncloa_aravaca_aravaca28023-55090523474_100500/',
 'https://www.pisos.com/comprar/apartamento-universidad_malasana28004-50046558633_101800/',
 'https://www.pisos.com/comprar/casa_pareada-moncloa_aravaca_aravaca28023-54260182234_100500/',
 'https://www.pisos.com/alquilar/apartamento-tetuan_almenara28046-55055259258_101800/',
 'https://www.pisos.com/comprar/piso-puerta_del_angel-55011467458_100200/',
 'https://www.pisos.com/alquilar/piso-nino_jesus28007-54247568000_100500/',
 'https://www.pisos.com/alquilar/piso-san_blas_salvador28027-55026715446_101000/',
 'https://www.pisos.com/comprar/atico-rio_rosas28003-53374775013_101800/',
 'https://www.pisos.com/comprar/apartamento-salamanca_castellana28006-49219197224_101800/',
 'https://www.pisos.com/alquilar/piso-guindalera28028-28351313995_100200/',
 'https://www.pisos.com/comprar/piso-cortes_huertas28014-55070501998_518589/',
 'https://www.pisos.com/comprar/piso-san_fermin28041-55096728194_100200/',
 'https://www.pisos.com/alquilar/piso-cortes_huertas28012-52557770099_104700/',
 'https://www.pisos.com/comprar/piso-las_aguilas28024-55026263331_100200/',
 'https://www.pisos.com/alquilar/piso-justicia_chueca28004-13405387302_996542/',
 'https://www.pisos.com/alquilar/piso-palomeras_bajas28018-50003428107_100500/',
 'https://www.pisos.com/alquilar/piso-carabanchel_comillas28019-55007326186_108900/',
 'https://www.pisos.com/comprar/atico-virgen_del_cortijo_manoteras28050-53360006830_101800/',
 'https://www.pisos.com/comprar/chalet_pareado-casa_de_campo28011-54212538005_100900/',
 'https://www.pisos.com/comprar/apartamento-chamberi_vallehermoso28003-53432635936_101800/',
 'https://www.pisos.com/comprar/piso-palomeras_bajas28018-55017200950_526848/',
 'https://www.pisos.com/comprar/piso-puente_de_vallecas_portazgo28018-55061568913_100200/',
 'https://www.pisos.com/comprar/piso-numancia28038-55039130276_100200/',
 'https://www.pisos.com/comprar/chalet-moncloa_aravaca_aravaca28023-43401017765_100500/',
 'https://www.pisos.com/comprar/apartamento-centro_embajadores_lavapies28012-54214885027_101800/',
 'https://www.pisos.com/comprar/piso-salamanca_castellana28006-55032640881_108900/',
 'https://www.pisos.com/alquilar/piso-goya28001-42522444122_100500/',
 'https://www.pisos.com/comprar/piso-los_berrocales_los_ahijones28031-5533610739_109700/',
 'https://www.pisos.com/comprar/apartamento-tetuan_almenara28029-54169485412_101800/',
 'https://www.pisos.com/comprar/atico-gaztambide28015-53358565985_101800/',
 'https://www.pisos.com/comprar/atico-chamartin_el_viso28036-55090239684_101800/',
 'https://www.pisos.com/comprar/chalet-guindalera28002-55033597964_102100/',
 'https://www.pisos.com/comprar/piso-rejas28022-55012610490_100500/',
 'https://www.pisos.com/alquilar/chalet_adosado-la_moraleja_distrito28109-41750538995_179400/',
 'https://www.pisos.com/alquilar/piso-ciudad_universitaria28035-54255954652_108900/',
 'https://www.pisos.com/alquilar/apartamento-palos_de_moguer28045-55038364678_109800/',
 'https://www.pisos.com/comprar/apartamento-trafalgar28010-51725388692_101800/',
 'https://www.pisos.com/alquilar/piso-rio_rosas28003-55090016020_100500/',
 'https://www.pisos.com/alquilar/piso-moscardo28026-55095373503_104700/',
 'https://www.pisos.com/alquilar/piso-justicia_chueca28004-54253768471_100500/',
 'https://www.pisos.com/comprar/apartamento-vicalvaro_ambroz28032-55084912833_105700/',
 'https://www.pisos.com/comprar/piso-justicia_chueca28004-53402663112_100500/',
 'https://www.pisos.com/comprar/piso-chamartin_ciudad_jardin28002-55029019792_100200/',
 'https://www.pisos.com/alquilar/piso-chamartin_el_viso28002-54215958688_100500/',
 'https://www.pisos.com/comprar/apartamento-jeronimos28014-50864467627_101800/',
 'https://www.pisos.com/comprar/casa-chamartin_hispanoamerica28016-19223849943_517093/',
 'https://www.pisos.com/alquilar/piso-justicia_chueca28004-54211041039_100500/',
 'https://www.pisos.com/alquilar/piso-la_moraleja_encinar_de_los_reyes28109-54192647977_100500/',
 'https://www.pisos.com/alquilar/piso-centro_embajadores_lavapies28012-54224542606_100500/',
 'https://www.pisos.com/alquilar/apartamento-adelfas28007-55020271395_993066/',
 'https://www.pisos.com/comprar/piso-nueva_espana28016-55019620102_100500/',
 'https://www.pisos.com/alquilar/piso-fuencarral_el_pardo_las_tablas28050-55005250661_109300/',
 'https://www.pisos.com/comprar/duplex-justicia_chueca28004-55090626117_522706/',
 'https://www.pisos.com/comprar/apartamento-ibiza28009-51705254650_101800/',
 'https://www.pisos.com/comprar/piso-vicalvaro_ambroz28032-55099518071_994867/',
 'https://www.pisos.com/comprar/apartamento-sol_barrio28013-53412777268_101800/',
 'https://www.pisos.com/comprar/piso-san_fermin28041-55092863324_100200/',
 'https://www.pisos.com/comprar/piso-trafalgar28010-55071327555_102100/',
 'https://www.pisos.com/comprar/piso-centro_palacio28005-55084446801_102100/',
 'https://www.pisos.com/alquilar/piso-trafalgar28010-55095982587_100200/',
 'https://www.pisos.com/alquilar/apartamento-salamanca_castellana28006-55002769795_101800/',
 'https://www.pisos.com/comprar/piso-san_blas_hellin28037-55038261473_100500/',
 'https://www.pisos.com/comprar/casa_adosada-moncloa_aravaca_aravaca28023-52564103397_101800/',
 'https://www.pisos.com/alquilar/piso-penagrande28035-55075741730_108900/',
 'https://www.pisos.com/comprar/piso-centro_embajadores_lavapies28012-51724913997_100500/',
 'https://www.pisos.com/alquilar/apartamento-rio_rosas28003-54168927250_991150/',
 'https://www.pisos.com/alquilar/piso-chamartin_hispanoamerica28036-55026252793_100500/',
 'https://www.pisos.com/alquilar/piso-fuente_del_berro28028-55054807059_109300/',
 'https://www.pisos.com/comprar/piso-san_fermin28041-48406057503_100200/',
 'https://www.pisos.com/comprar/duplex-rio_rosas28003-55098432586_520200/',
 'https://www.pisos.com/alquilar/piso-carabanchel_san_isidro28019-55060149077_108900/',
 'https://www.pisos.com/comprar/piso-centro_embajadores_lavapies28012-44258552242_102200/',
 'https://www.pisos.com/comprar/piso-pavones-55049961537_100200/',
 'https://www.pisos.com/alquilar/piso-alameda_de_osuna_barrio-54207371987_108900/',
 'https://www.pisos.com/alquilar/piso-trafalgar28010-55081191769_100500/',
 'https://www.pisos.com/comprar/piso-ibiza-55033437837_106600/',
 'https://www.pisos.com/comprar/piso-chamartin_hispanoamerica28016-55049242573_100500/',
 'https://www.pisos.com/alquilar/piso-universidad_malasana28015-55036442564_100500/',
 'https://www.pisos.com/comprar/piso-las_aguilas28044-54172960475_100200/',
 'https://www.pisos.com/alquilar/piso-chamartin_ciudad_jardin28002-55054947120_100500/',
 'https://www.pisos.com/alquilar/chalet_pareado-la_moraleja_encinar_de_los_reyes-904123466_179400/',
 'https://www.pisos.com/alquilar/piso-goya28028-55039655844_100500/',
 'https://www.pisos.com/comprar/apartamento-chamartin_el_viso28006-52581779550_101800/',
 'https://www.pisos.com/alquilar/piso-jeronimos28009-55071327014_108900/',
 'https://www.pisos.com/comprar/piso-retiro_pacifico-55056560939_106600/',
 'https://www.pisos.com/comprar/piso-adelfas28007-55084647445_105100/',
 'https://www.pisos.com/comprar/piso-pilar28029-54206396309_100200/',
 'https://www.pisos.com/alquilar/estudio-puerta_del_angel-53345384627_104700/',
 'https://www.pisos.com/comprar/piso-chamberi_arapiles28015-55071476127_100500/',
 'https://www.pisos.com/alquilar/piso-montecarmelo28049-55091202715_102100/',
 'https://www.pisos.com/comprar/piso-recoletos28009-53421246932_108900/',
 'https://www.pisos.com/comprar/piso-orcasur28041-54220639041_100200/',
 'https://www.pisos.com/comprar/apartamento-goya28009-55068474299_101800/',
 'https://www.pisos.com/alquilar/piso-lista_barrio28006-55026183531_108900/',
 'https://www.pisos.com/comprar/piso-centro_palacio28005-55074772778_510380/',
 'https://www.pisos.com/comprar/piso-goya28006-54245878731_100500/',
 'https://www.pisos.com/comprar/piso-universidad_malasana28004-55019440874_100500/',
 'https://www.pisos.com/comprar/apartamento-recoletos28001-55022098533_101800/',
 'https://www.pisos.com/alquilar/piso-villa_de_vallecas_santa_eugenia28031-55003272349_108900/',
 'https://www.pisos.com/alquilar/piso-goya28001-15062498673_100500/',
 'https://www.pisos.com/alquilar/piso-carabanchel_vista_alegre28025-55036580127_108900/',
 'https://www.pisos.com/comprar/piso-palomeras_sureste28038-54244898113_100200/',
 'https://www.pisos.com/comprar/piso-palos_de_moguer28045-55015526455_100200/',
 'https://www.pisos.com/alquilar/piso-guindalera28028-55004464525_440000/',
 'https://www.pisos.com/comprar/piso-tetuan_cuatro_caminos28020-55068219850_100500/',
 'https://www.pisos.com/alquilar/piso-guindalera28028-55058034927_100200/',
 'https://www.pisos.com/comprar/atico-justicia_chueca28004-50840403544_101800/',
 'https://www.pisos.com/alquilar/apartamento-lista_barrio28001-55068458679_101800/',
 'https://www.pisos.com/comprar/piso-trafalgar28010-55057032429_108900/',
 'https://www.pisos.com/comprar/atico-chamberi_almagro28010-55003652048_101800/',
 'https://www.pisos.com/alquilar/piso-centro_embajadores_lavapies28012-54235272105_518209/',
 'https://www.pisos.com/alquilar/piso-valdebebas_valdefuentes28055-55014182173_100500/',
 'https://www.pisos.com/comprar/piso-retiro_estrella28007-54167429964_100200/',
 'https://www.pisos.com/alquilar/atico-arganzuela_delicias-55048070580_108900/',
 'https://www.pisos.com/comprar/piso-goya28001-54188361932_109300/',
 'https://www.pisos.com/alquilar/piso-opanel28019-54253636612_109300/',
 'https://www.pisos.com/alquilar/apartamento-lista_barrio28006-55080453230_100500/',
 'https://www.pisos.com/comprar/piso-los_berrocales_los_ahijones28031-5518980596_109700/',
 'https://www.pisos.com/comprar/piso-palomeras_sureste28031-54229818623_994811/',
 'https://www.pisos.com/alquilar/piso-nueva_espana28036-55042357356_518209/',
 'https://www.pisos.com/alquilar/apartamento-goya28009-54246787991_101800/',

In [36]:
to_update = set_new & set_old
to_update

{'https://www.pisos.com/alquilar/piso-gaztambide28015-30000292679_100500/',
 'https://www.pisos.com/comprar/piso-salamanca_castellana28006-44202123780_109100/',
 'https://www.pisos.com/comprar/piso-carabanchel_san_isidro28019-42590272502_100200/',
 'https://www.pisos.com/comprar/piso-rios_rosas28003-48430605870_109300/',
 'https://www.pisos.com/comprar/piso-chamartin_el_viso28002-54264885488_992392/',
 'https://www.pisos.com/comprar/piso-justicia_chueca28004-50926400471_102100/',
 'https://www.pisos.com/comprar/piso-ciudad_lineal_pueblo_nuevo28037-37541028738_102100/',
 'https://www.pisos.com/alquilar/piso-tetuan_cuatro_caminos28020-42516904594_100500/',
 'https://www.pisos.com/alquilar/apartamento-puerta_del_angel-54220439892_101800/',
 'https://www.pisos.com/comprar/atico-costillares-1772946757_109700/',
 'https://www.pisos.com/comprar/casa_pareada-moncloa_aravaca_aravaca28023-5056411757_100500/',
 'https://www.pisos.com/comprar/piso-costillares28033-53355745514_109300/',
 'https://www.pisos.com/comprar/piso-jeronimos28014-54211268947_100500/',
 'https://www.pisos.com/alquilar/piso-chamberi_arapiles28015-42594932071_100500/',
 'https://www.pisos.com/alquilar/piso-puerta_bonita28025-54217758501_105700/',
 'https://www.pisos.com/alquilar/piso-salamanca_castellana28006-54223404427_108900/',
 'https://www.pisos.com/comprar/piso-jeronimos28014-47544980732_500970/',
 'https://www.pisos.com/alquilar/piso-salamanca_castellana28006-54175561100_100500/',
 'https://www.pisos.com/comprar/piso-universidad_malasana28004-54182160408_100200/',
 'https://www.pisos.com/comprar/piso-recoletos28009-52582927579_149200/',
 'https://www.pisos.com/alquilar/piso-chamberi_arapiles28015-53333677923_521707/',
 'https://www.pisos.com/comprar/casa-ibiza28009-51736860826_106700/',
 'https://www.pisos.com/comprar/piso-tetuan_cuatro_caminos28046-51759530512_100500/',
 'https://www.pisos.com/comprar/piso-numancia28038-54254620471_526615/',
 'https://www.pisos.com/alquilar/piso-goya28006-48427094323_100500/',
 'https://www.pisos.com/comprar/piso-goya28009-51709596016_100500/',
 'https://www.pisos.com/comprar/atico-rios_rosas28003-49257554351_101800/',
 'https://www.pisos.com/alquilar/piso-salamanca_castellana28006-54185383221_996542/',
 'https://www.pisos.com/comprar/piso-chamartin_el_viso28002-24178797472_996542/',
 'https://www.pisos.com/comprar/piso-goya28009-53342618290_100200/',
 'https://www.pisos.com/comprar/duplex-centro_embajadores_lavapies28012-52556492967_522706/',
 'https://www.pisos.com/comprar/piso-carabanchel_buenavista28044-7527580186_996901/',
 'https://www.pisos.com/alquilar/apartamento-universidad_malasana28004-52572947424_101800/',
 'https://www.pisos.com/comprar/piso-lista_barrio28006-53345050413_100500/',
 'https://www.pisos.com/alquilar/piso-nino_jesus28007-43409690942_100500/',
 'https://www.pisos.com/comprar/piso-justicia_chueca28004-52535829307_102100/',
 'https://www.pisos.com/comprar/piso-recoletos28009-45922635651_524671/',
 'https://www.pisos.com/alquilar/apartamento-sol_barrio28012-54191179196_101800/',
 'https://www.pisos.com/comprar/piso-puerta_bonita28025-45043176222_528057/',
 'https://www.pisos.com/comprar/piso-centro_palacio28005-52527271657_102100/',
 'https://www.pisos.com/comprar/piso-villaverde_san_andres28021-37537974067_100200/',
 'https://www.pisos.com/comprar/piso-ibiza28009-50096855058_100500/',
 'https://www.pisos.com/alquilar/piso-chamberi_almagro28010-42512363310_100500/',
 'https://www.pisos.com/alquilar/piso-salamanca_castellana28006-54207913656_100500/',
 'https://www.pisos.com/comprar/piso-usera_pradolongo28026-48401916295_100200/',
 'https://www.pisos.com/alquilar/piso-villaverde_los_rosales28021-30846610173_100500/',
 'https://www.pisos.com/comprar/apartamento-centro_embajadores_lavapies28012-51716399623_994867/',
 'https://www.pisos.com/alquilar/piso-guindalera28002-51765091722_102100/',
 'https://www.pisos.com/comprar/piso-goya28001-53433134778_514774/',
 'https://www.pisos.com/comprar/piso-ciudad_lineal_pueblo_nuevo28017-52558236201_525207/',
 'https://www.pisos.com/alquilar/piso-centro_palacio28013-52589998634_102100/',
 'https://www.pisos.com/alquilar/piso-tetuan_almenara28029-52591823900_522531/',
 'https://www.pisos.com/alquilar/piso-centro_embajadores_lavapies28012-52590196823_109800/',
 'https://www.pisos.com/comprar/piso-ciudad_lineal_pueblo_nuevo28017-53417102917_105100/',
 'https://www.pisos.com/alquilar/apartamento-goya28001-52573417863_106000/',
 'https://www.pisos.com/alquilar/piso-rios_rosas28003-44240566500_100500/',
 'https://www.pisos.com/alquilar/piso-barrio_de_salamanca_castellana28006-53343512327_100500/',
 'https://www.pisos.com/alquilar/piso-zofio28026-54214393326_104700/',
 'https://www.pisos.com/comprar/piso-recoletos28001-47524955370_149200/',
 'https://www.pisos.com/alquilar/piso-tetuan_cuatro_caminos28020-43359261792_100500/',
 'https://www.pisos.com/alquilar/piso-centro_palacio28013-51757479206_102100/',
 'https://www.pisos.com/comprar/piso-imperial28005-54172060844_100500/',
 'https://www.pisos.com/comprar/piso-imperial28005-54231429386_100500/',
 'https://www.pisos.com/comprar/piso-guindalera28028-50923038836_100500/',
 'https://www.pisos.com/comprar/atico-chamartin_prosperidad28002-50034202224_100500/',
 'https://www.pisos.com/alquilar/piso-justicia_chueca28004-45833694266_100500/',
 'https://www.pisos.com/alquilar/estudio-salamanca_castellana28006-47591624710_108900/',
 'https://www.pisos.com/comprar/piso-valdeacederas28039-53385634723_521737/',
 'https://www.pisos.com/alquilar/piso-centro_palacio28005-51685328004_102100/',
 'https://www.pisos.com/alquilar/apartamento-tetuan_almenara28029-42594441920_101800/',
 'https://www.pisos.com/comprar/piso-centro_palacio28005-48394768291_106700/',
 'https://www.pisos.com/comprar/piso-villaverde_los_rosales28021-53385157432_100500/',
 'https://www.pisos.com/alquilar/duplex-barrio_de_salamanca_castellana28006-52500364975_520609/',
 'https://www.pisos.com/comprar/piso-sol_barrio28013-52567923633_109300/',
 'https://www.pisos.com/comprar/piso-arcos28032-53397418270_100200/',
 'https://www.pisos.com/alquilar/piso-justicia_chueca28004-24254231384_996542/',
 'https://www.pisos.com/comprar/piso-palomeras_bajas28018-49232196713_100200/',
 'https://www.pisos.com/comprar/piso-castillejos28020-54224906128_100500/',
 'https://www.pisos.com/alquilar/piso-zofio28026-52535158988_104700/',
 'https://www.pisos.com/comprar/piso-jeronimos28014-31755755043_100500/',
 'https://www.pisos.com/comprar/piso-nueva_espana28036-62593323834_149200/',
 'https://www.pisos.com/alquilar/apartamento-universidad_malasana28004-46760898410_101800/',
 'https://www.pisos.com/alquilar/estudio-guindalera28028-53360264268_104700/',
 'https://www.pisos.com/alquilar/piso-castillejos28020-54234835785_108900/',
 'https://www.pisos.com/comprar/casa_pareada-penagrande28035-53391833090_101800/',
 'https://www.pisos.com/comprar/piso-goya28006-51678418632_102100/',
 'https://www.pisos.com/comprar/piso-moncloa_aravaca_aravaca28023-4696645935_109700/',
 'https://www.pisos.com/comprar/atico-san_blas_salvador28027-52552431513_100500/',
 'https://www.pisos.com/alquilar/piso-jeronimos28009-42576439443_100500/',
 'https://www.pisos.com/comprar/piso-goya28006-51691999815_102100/',
 'https://www.pisos.com/comprar/piso-palomeras_sureste28031-53368241646_100500/',
 'https://www.pisos.com/alquilar/chalet_unifamiliar-castillejos28020-51727367350_996542/',
 'https://www.pisos.com/alquilar/apartamento-tetuan_almenara28046-54250493389_101800/',
 'https://www.pisos.com/alquilar/piso-castilla28036-53383736142_100500/',
 'https://www.pisos.com/alquilar/piso-salamanca_castellana28006-54235652798_108900/',
 'https://www.pisos.com/comprar/piso-chamartin_prosperidad28002-53374250111_100200/',
 'https://www.pisos.com/comprar/piso-barrio_de_salamanca_lista28006-52591290541_524350/',
 'https://www.pisos.com/alquilar/piso-centro_palacio28013-51698164571_102100/',
 'https://www.pisos.com/comprar/piso-lista_barrio28028-50901457226_109300/',
 'https://www.pisos.com/alquilar/atico-el_canaveral-40900638027_100500/',
 'https://www.pisos.com/comprar/piso-villa_de_vallecas_santa_eugenia28031-51763736936_528352/',
 'https://www.pisos.com/comprar/piso-moncloa_aravaca_arguelles28008-24173811167_517093/',
 'https://www.pisos.com/alquilar/piso-chamberi_almagro28010-42564341839_100500/',
 'https://www.pisos.com/alquilar/apartamento-almendrales28026-52546983302_109800/',
 'https://www.pisos.com/comprar/piso-casco_historico_de_vallecas28031-51743566916_105100/',
 'https://www.pisos.com/comprar/chalet-valdezarza28035-54202959331_100500/',
 'https://www.pisos.com/alquilar/apartamento-chamberi_almagro28010-31749765096_996542/',
 'https://www.pisos.com/alquilar/piso-chamberi_almagro28010-54185632813_100500/',
 'https://www.pisos.com/comprar/piso-barrio_de_salamanca_lista28006-53384415350_100500/',
 'https://www.pisos.com/alquilar/piso-villaverde_san_andres28021-48350457570_100500/',
 'https://www.pisos.com/alquilar/apartamento-universidad_malasana28004-38430850360_101800/',
 'https://www.pisos.com/comprar/piso-recoletos28001-52522604872_101800/',
 'https://www.pisos.com/alquilar/piso-recoletos28001-42537940081_100500/',
 'https://www.pisos.com/alquilar/piso-chamberi_almagro28010-24254001404_100500/',
 'https://www.pisos.com/alquilar/apartamento-trafalgar28010-53377177357_101800/',
 'https://www.pisos.com/comprar/piso-gaztambide28015-43366692243_526309/',
 'https://www.pisos.com/alquilar/apartamento-sol_barrio28005-50077129007_100500/',
 'https://www.pisos.com/comprar/piso-salamanca_castellana28006-54177338585_100500/',
 'https://www.pisos.com/comprar/chalet_adosado-nueva_espana28036-945856909447899_109700/',
 'https://www.pisos.com/comprar/piso-barrio_de_salamanca_castellana28006-51696060226_109300/',
 'https://www.pisos.com/comprar/piso-lista_barrio28006-54237852162_100500/',
 'https://www.pisos.com/comprar/piso-chamberi_almagro28010-53398079869_521737/',
 'https://www.pisos.com/comprar/piso-centro_embajadores_lavapies28012-54239872464_100500/',
 'https://www.pisos.com/comprar/piso-latina_campamento28024-54182165686_100200/',
 'https://www.pisos.com/comprar/piso-justicia_chueca28001-41763207757_102100/',
 'https://www.pisos.com/alquilar/piso-universidad_malasana28004-36691645811_100500/',
 'https://www.pisos.com/comprar/piso-barrio_de_salamanca_castellana28006-51676255126_109300/',
 'https://www.pisos.com/alquilar/estudio-justicia_chueca28004-53407965515_100500/',
 'https://www.pisos.com/alquilar/apartamento-chamartin_el_viso28006-46726152745_996542/',
 'https://www.pisos.com/comprar/piso-chamberi_almagro28010-51711170836_101800/',
 'https://www.pisos.com/comprar/piso-chamartin_hispanoamerica28036-41719592126_149200/',
 'https://www.pisos.com/comprar/piso-chamartin_prosperidad28043-41731912436_102100/',
 'https://www.pisos.com/comprar/apartamento-justicia_chueca28004-53363091324_992672/',
 'https://www.pisos.com/comprar/piso-justicia_chueca28004-53416906945_102100/',
 'https://www.pisos.com/alquilar/chalet-castilla28034-52573738263_102100/',
 'https://www.pisos.com/comprar/piso-arganzuela_delicias-54206555438_500823/',
 'https://www.pisos.com/comprar/piso-goya28009-51712844348_100500/',
 'https://www.pisos.com/comprar/piso-justicia_chueca28001-52505072844_102100/',
 'https://www.pisos.com/comprar/piso-recoletos28001-50002137631_149200/',
 'https://www.pisos.com/alquilar/apartamento-universidad_malasana28004-40933041284_527206/',
 'https://www.pisos.com/comprar/piso-nino_jesus28007-51687229194_100500/',
 'https://www.pisos.com/alquilar/piso-centro_palacio28013-53405313950_102100/',
 'https://www.pisos.com/comprar/apartamento-lista_barrio28006-54236613022_100500/',
 'https://www.pisos.com/comprar/piso-justicia_chueca28004-49223942295_100500/',
 'https://www.pisos.com/alquilar/piso-justicia_chueca28001-53339848190_102100/',
 'https://www.pisos.com/alquilar/apartamento-bellas_vistas28039-52509880125_101800/',
 'https://www.pisos.com/alquilar/piso-gaztambide28015-54197112228_998787/',
 'https://www.pisos.com/comprar/piso-recoletos28001-50063468552_100500/',
 'https://www.pisos.com/alquilar/piso-imperial28005-43383484081_100200/',
 'https://www.pisos.com/comprar/piso-valdeacederas28029-52526405164_104700/',
 'https://www.pisos.com/alquilar/apartamento-sanchinarro28050-54245098062_992099/',
 'https://www.pisos.com/comprar/piso-chamberi_vallehermoso28003-49205296635_100500/',
 'https://www.pisos.com/comprar/piso-recoletos28001-38404863871_100500/',
 'https://www.pisos.com/comprar/piso-rios_rosas28003-52522945736_100500/',
 'https://www.pisos.com/comprar/piso-goya28006-53399348124_102100/',
 'https://www.pisos.com/comprar/piso-chamberi_almagro28010-53379443228_100500/',
 'https://www.pisos.com/comprar/piso-chamartin_el_viso28036-50852411305_149200/',
 'https://www.pisos.com/comprar/duplex-sol_barrio28012-53364424889_100500/',
 'https://www.pisos.com/comprar/piso-moncloa_aravaca_aravaca28023-4745902236_109700/',
 'https://www.pisos.com/comprar/piso-justicia_chueca28004-39200448773_100500/',
 'https://www.pisos.com/comprar/piso-salamanca_castellana28006-945856909381506_109700/',
 'https://www.pisos.com/comprar/piso-centro_embajadores_lavapies28005-53414174310_101000/',
 'https://www.pisos.com/alquilar/piso-centro_palacio28013-52535297241_109800/',
 'https://www.pisos.com/alquilar/piso-justicia_chueca28001-99246145612_102100/',
 'https://www.pisos.com/alquilar/apartamento-chamartin_ciudad_jardin28002-54241699241_101800/',
 'https://www.pisos.com/comprar/piso-castilla28034-52584493308_524228/',
 'https://www.pisos.com/comprar/apartamento-justicia_chueca28004-53385745677_992672/',
 'https://www.pisos.com/comprar/estudio-palos_de_moguer28045-53371918670_100500/',
 'https://www.pisos.com/comprar/piso-goya28001-50893712938_108500/',
 'https://www.pisos.com/comprar/piso-villaverde_san_andres28021-53376124991_523292/',
 'https://www.pisos.com/comprar/piso-virgen_del_cortijo_manoteras28050-53373099699_100500/',
 'https://www.pisos.com/comprar/piso-recoletos28001-53433311209_100500/',
 'https://www.pisos.com/comprar/piso-chamberi_arapiles28015-51760348529_996542/',
 'https://www.pisos.com/alquilar/piso-goya28001-54188077257_100500/',
 'https://www.pisos.com/alquilar/piso-centro_palacio28013-53365803012_102100/',
 'https://www.pisos.com/comprar/piso-lista_barrio28006-50072086610_108900/',
 'https://www.pisos.com/alquilar/piso-goya28009-53421756396_108900/',
 'https://www.pisos.com/comprar/piso-lista_barrio28001-53377709924_100500/',
 'https://www.pisos.com/alquilar/atico-guindalera28028-54198989265_108500/',
 'https://www.pisos.com/alquilar/piso-trafalgar28010-54260489099_104700/',
 'https://www.pisos.com/comprar/piso-fuentelarreina28035-54262950120_101800/',
 'https://www.pisos.com/comprar/chalet-san_blas_simancas28037-5211136814_109700/',
 'https://www.pisos.com/comprar/piso-san_blas_canillejas28022-53358587300_100200/',
 'https://www.pisos.com/comprar/piso-cortes_huertas28014-50845967639_109300/',
 'https://www.pisos.com/comprar/atico-chamberi_almagro28010-54170091891_100500/',
 'https://www.pisos.com/alquilar/apartamento-casco_historico_de_barajas-44172157379_101800/',
 'https://www.pisos.com/alquilar/piso-sanchinarro28050-45882690937_100500/',
 'https://www.pisos.com/comprar/piso-universidad_malasana28004-52544392354_100500/',
 'https://www.pisos.com/comprar/piso-lista_barrio28006-54237877132_520200/',
 'https://www.pisos.com/alquilar/estudio-centro_palacio28005-53422108671_104700/',
 'https://www.pisos.com/alquilar/piso-chamberi_almagro28010-54214231089_100500/',
 'https://www.pisos.com/comprar/piso-moncloa_aravaca_arguelles28008-52534357840_992673/',
 'https://www.pisos.com/comprar/piso-tetuan_cuatro_caminos28020-52542906712_100200/',
 'https://www.pisos.com/comprar/piso-ensanche_de_vallecas_valdecarros28051-54248158558_100500/',
 'https://www.pisos.com/alquilar/piso-chamberi_arapiles28015-54199973226_108900/',
 'https://www.pisos.com/comprar/chalet-fuencarral_el_pardo_el_pardo28035-45907955458_102100/',
 'https://www.pisos.com/alquilar/atico-trafalgar28010-38427667709_101800/',
 'https://www.pisos.com/alquilar/piso-goya28009-47532022933_108900/',
 'https://www.pisos.com/comprar/piso-palomeras_sureste28018-54242837550_100200/',
 'https://www.pisos.com/comprar/piso-centro_palacio28005-51704323149_102100/',
 'https://www.pisos.com/alquilar/apartamento-tetuan_cuatro_caminos28020-50903901077_101800/',
 'https://www.pisos.com/comprar/piso-rejas28022-53411254310_104700/',
 'https://www.pisos.com/comprar/chalet-valdemarin-51717246069_102100/',
 'https://www.pisos.com/comprar/apartamento-sanchinarro28050-54247072740_101800/',
 'https://www.pisos.com/alquilar/piso-chamartin_hispanoamerica28016-53416155707_108900/',
 'https://www.pisos.com/comprar/piso-chamartin_el_viso28002-54235721567_100500/',
 'https://www.pisos.com/alquilar/estudio-chamartin_hispanoamerica28016-43348913744_996542/',
 'https://www.pisos.com/comprar/piso-ibiza28009-51695850592_102100/',
 'https://www.pisos.com/comprar/piso-chopera28045-52503902997_523563/',
 'https://www.pisos.com/comprar/piso-moncloa_aravaca_arguelles28008-53372228920_100500/',
 'https://www.pisos.com/comprar/piso-centro_embajadores_lavapies28012-48420384297_101800/',
 'https://www.pisos.com/comprar/piso-palos_de_moguer28045-54236417319_100500/',
 'https://www.pisos.com/comprar/piso-goya28001-50019570115_108900/',
 'https://www.pisos.com/comprar/piso-jeronimos28014-48403298558_149200/',
 'https://www.pisos.com/alquilar/piso-recoletos28001-42521566077_100500/',
 'https://www.pisos.com/comprar/piso-justicia_chueca28001-45842498762_102100/',
 'https://www.pisos.com/alquilar/piso-nino_jesus28009-54189321924_109100/',
 'https://www.pisos.com/alquilar/piso-lista_barrio28006-53344772931_100500/',
 'https://www.pisos.com/comprar/piso-goya28006-54226261056_524350/',
 'https://www.pisos.com/comprar/piso-salamanca_castellana28006-48423651125_100500/',
 'https://www.pisos.com/comprar/piso-sol_barrio28013-26677372255_100500/',
 'https://www.pisos.com/comprar/piso-cortes_huertas28014-53394483457_100500/',
 'https://www.pisos.com/comprar/piso-carabanchel_san_isidro28019-53422193009_100500/',
 'https://www.pisos.com/alquilar/piso-chamberi_almagro28010-846021493_100500/',
 'https://www.pisos.com/alquilar/piso-cortes_huertas28014-54211838412_104700/',
 'https://www.pisos.com/comprar/chalet_unifamiliar-chamartin_el_viso28002-39186461710_149200/',
 'https://www.pisos.com/alquilar/apartamento-sol_barrio28012-46738387641_519303/',
 'https://www.pisos.com/alquilar/piso-nueva_espana28036-855106218_100500/',
 'https://www.pisos.com/comprar/chalet-chamartin_prosperidad28043-48365035737_102100/',
 'https://www.pisos.com/comprar/piso-latina_carmenes28047-53345646611_100500/',
 'https://www.pisos.com/alquilar/piso-numancia28038-54243510241_100500/',
 'https://www.pisos.com/comprar/piso-universidad_malasana28015-47514945452_100500/',
 'https://www.pisos.com/comprar/piso-montecarmelo28050-54252460807_102100/',
 'https://www.pisos.com/alquilar/piso-nueva_espana28036-51728710760_996542/',
 'https://www.pisos.com/alquilar/apartamento-chamartin_hispanoamerica28036-54174933865_101800/',
 'https://www.pisos.com/alquilar/piso-universidad_malasana28015-54216831229_528990/',
 'https://www.pisos.com/alquilar/piso-chamberi_almagro28010-53417197554_100500/',
 'https://www.pisos.com/comprar/piso-justicia_chueca28004-52542871359_149200/',
 'https://www.pisos.com/alquilar/apartamento-valdeacederas28039-50860294291_101800/',
 'https://www.pisos.com/alquilar/piso-ciudad_universitaria28040-53423816424_100500/',
 'https://www.pisos.com/comprar/piso-goya28006-50902833847_100500/',
 'https://www.pisos.com/comprar/piso-centro_palacio28005-54240185844_102100/',
 'https://www.pisos.com/comprar/piso-chamberi_almagro28010-49252517083_100500/',
 'https://www.pisos.com/comprar/chalet-moncloa_aravaca_aravaca28023-4726633940_109700/',
 'https://www.pisos.com/alquilar/piso-trafalgar28010-54209170302_100500/',

In [37]:
to_remove = set_old - set_new
to_remove

{'https://www.pisos.com/comprar/piso-centro_palacio28005-54245546427_102100/',
 'https://www.pisos.com/alquilar/piso-pinar_del_rey28033-54224164144_108900/',
 'https://www.pisos.com/comprar/piso-palomeras_bajas28053-51719687352_100500/',
 'https://www.pisos.com/comprar/piso-ventas28017-46738427271_109300/',
 'https://www.pisos.com/comprar/piso-villaverde_los_angeles28041-53371492308_108900/',
 'https://www.pisos.com/comprar/piso-carabanchel_buenavista28044-52543062111_100200/',
 'https://www.pisos.com/comprar/piso-centro_embajadores_lavapies28012-54175991279_100500/',
 'https://www.pisos.com/comprar/piso-salamanca_castellana28006-50921051120_100500/',
 'https://www.pisos.com/comprar/piso-villaverde_san_cristobal-49188528002_107000/',
 'https://www.pisos.com/alquilar/piso-justicia_chueca28004-945856909480195_109700/',
 'https://www.pisos.com/comprar/duplex-chamberi_almagro28010-50873104592_100500/',
 'https://www.pisos.com/alquilar/piso-goya28006-54266155365_108900/',
 'https://www.pisos.com/alquilar/apartamento-san_blas_salvador28027-53337746717_101800/',
 'https://www.pisos.com/comprar/piso-carabanchel_buenavista28044-52506930808_100500/',
 'https://www.pisos.com/alquilar/estudio-gaztambide28015-53423811101_100500/',
 'https://www.pisos.com/comprar/piso-centro_embajadores_lavapies28012-54196603247_108500/',
 'https://www.pisos.com/alquilar/piso-los_berrocales_los_ahijones28031-54263732985_108900/',
 'https://www.pisos.com/comprar/piso-lista_barrio28006-50877732291_100200/',
 'https://www.pisos.com/alquilar/piso-fuencarral_el_pardo_valverde28034-54169671918_108900/',
 'https://www.pisos.com/alquilar/estudio-universidad_malasana28015-52517040783_104700/',
 'https://www.pisos.com/comprar/piso-cortes_huertas28014-53406447604_108500/',
 'https://www.pisos.com/alquilar/apartamento-nino_jesus28009-52571320373_100500/',
 'https://www.pisos.com/alquilar/piso-imperial28019-51691898221_102100/',
 'https://www.pisos.com/alquilar/piso-valdezarza28035-54208276637_108900/',
 'https://www.pisos.com/alquilar/piso-universidad_malasana28004-54215040293_100500/',
 'https://www.pisos.com/comprar/piso-casco_historico_de_barajas-54245434891_528332/',
 'https://www.pisos.com/alquilar/piso-puerta_del_angel-54228066676_108900/',
 'https://www.pisos.com/alquilar/apartamento-goya28009-53390666562_101800/',
 'https://www.pisos.com/comprar/apartamento-san_blas_simancas28037-54200838018_100500/',
 'https://www.pisos.com/comprar/apartamento-justicia_chueca28004-53364659186_992672/',
 'https://www.pisos.com/comprar/chalet-nino_jesus28007-48423154258_100500/',
 'https://www.pisos.com/alquilar/estudio-chamberi_arapiles28015-52561911495_104700/',
 'https://www.pisos.com/alquilar/piso-trafalgar28010-52547498238_108900/',
 'https://www.pisos.com/comprar/piso-orcasur28041-52575331099_100500/',
 'https://www.pisos.com/alquilar/piso-piovera28043-54172612130_108900/',
 'https://www.pisos.com/comprar/casa-san_blas_simancas28037-54187443772_520499/',
 'https://www.pisos.com/comprar/loft-san_blas_simancas28037-50857695982_100200/',
 'https://www.pisos.com/comprar/piso-pilar28029-52532566309_100200/',
 'https://www.pisos.com/comprar/piso-recoletos28001-53401154086_100500/',
 'https://www.pisos.com/comprar/piso-justicia_chueca28004-46694875680_100500/',
 'https://www.pisos.com/comprar/piso-puerta_bonita28025-53409991353_100500/',
 'https://www.pisos.com/comprar/chalet_adosado-fuencarral_el_pardo_valverde28034-54179075534_105700/',
 'https://www.pisos.com/alquilar/piso-trafalgar28010-42511016128_100500/',
 'https://www.pisos.com/alquilar/estudio-chamberi_arapiles28015-53355918255_104700/',
 'https://www.pisos.com/comprar/piso-ciudad_lineal_pueblo_nuevo28017-54254590511_101800/',
 'https://www.pisos.com/alquilar/piso-casco_historico_de_vallecas28031-38413095926_100500/',
 'https://www.pisos.com/alquilar/piso-universidad_malasana28015-49257651013_529055/',
 'https://www.pisos.com/alquilar/piso-sol_barrio28012-53396770832_100500/',
 'https://www.pisos.com/comprar/atico-chamberi_vallehermoso28003-52539336276_100500/',
 'https://www.pisos.com/comprar/atico-lista_barrio28006-54250701947_100500/',
 'https://www.pisos.com/alquilar/piso-tetuan_almenara28046-53402903761_108900/',
 'https://www.pisos.com/alquilar/piso-barrio_de_salamanca_castellana28006-52519149286_108900/',
 'https://www.pisos.com/comprar/piso-puente_de_vallecas_portazgo28018-54198033252_109300/',
 'https://www.pisos.com/alquilar/piso-centro_embajadores_lavapies28012-35005608639_100200/',
 'https://www.pisos.com/comprar/piso-jeronimos28014-50915957621_149200/',
 'https://www.pisos.com/alquilar/piso-sol_barrio28014-45866829261_100500/',
 'https://www.pisos.com/alquilar/piso-ventas28017-54252436881_108900/',
 'https://www.pisos.com/alquilar/piso-ibiza28009-54220001242_109800/',
 'https://www.pisos.com/comprar/piso-san_blas_rosas28022-51696802584_100200/',
 'https://www.pisos.com/comprar/piso-puente_de_vallecas_portazgo28018-52533793998_100500/',
 'https://www.pisos.com/comprar/piso-centro_palacio28005-54230710031_102100/',
 'https://www.pisos.com/comprar/piso-latina_carmenes28047-54185886219_108500/',
 'https://www.pisos.com/comprar/piso-recoletos28001-50069965739_100500/',
 'https://www.pisos.com/comprar/piso-recoletos28001-53363934828_108900/',
 'https://www.pisos.com/comprar/piso-ibiza28009-47563309334_108900/',
 'https://www.pisos.com/comprar/piso-puente_de_vallecas_san_diego28053-53389300187_100200/',
 'https://www.pisos.com/alquilar/piso-hortaleza_canillas28043-54196913478_996542/',
 'https://www.pisos.com/comprar/piso-penagrande28035-49170443855_100200/',
 'https://www.pisos.com/comprar/piso-fontarron-54256995604_100200/',
 'https://www.pisos.com/comprar/piso-fuente_del_berro28028-53355538875_101800/',
 'https://www.pisos.com/comprar/piso-carabanchel_san_isidro28019-53356435993_528950/',
 'https://www.pisos.com/alquilar/piso-rios_rosas28003-42594169395_100500/',
 'https://www.pisos.com/comprar/piso-concepcion-48401297191_100200/',
 'https://www.pisos.com/comprar/piso-castilla28036-50001195771_104700/',
 'https://www.pisos.com/alquilar/apartamento-concepcion28027-53369050952_101800/',
 'https://www.pisos.com/comprar/piso-goya28009-54254756931_100500/',
 'https://www.pisos.com/alquilar/piso-chamberi_almagro28010-42596572500_100500/',
 'https://www.pisos.com/comprar/piso-centro_palacio28005-52572624178_108500/',
 'https://www.pisos.com/alquilar/piso-rio_rosas28003-53366218558_108900/',
 'https://www.pisos.com/comprar/piso-cortes_huertas28014-53384780003_100500/',
 'https://www.pisos.com/alquilar/piso-arganzuela_delicias-54226085766_108900/',
 'https://www.pisos.com/comprar/piso-vicalvaro_ambroz28032-52570160738_100500/',
 'https://www.pisos.com/alquilar/apartamento-goya28001-54221877210_101800/',
 'https://www.pisos.com/comprar/piso-universidad_malasana28015-48359925980_102100/',
 'https://www.pisos.com/comprar/piso-san_blas_hellin28037-51736736313_100200/',
 'https://www.pisos.com/alquilar/piso-montecarmelo28050-53360934566_102100/',
 'https://www.pisos.com/comprar/piso-centro_embajadores_lavapies28012-54225504298_100500/',
 'https://www.pisos.com/comprar/piso-san_blas_canillejas28022-51680791436_104700/',
 'https://www.pisos.com/comprar/piso-vinateros-54185705533_108500/',
 'https://www.pisos.com/alquilar/piso-chamberi_arapiles28015-42597387694_100500/',
 'https://www.pisos.com/comprar/piso-puente_de_vallecas_portazgo28018-54260918835_109300/',
 'https://www.pisos.com/comprar/atico-ensanche_de_vallecas_valdecarros28051-54230471272_100500/',
 'https://www.pisos.com/alquilar/apartamento-goya28001-54229529044_101800/',
 'https://www.pisos.com/comprar/piso-pilar28034-51695276363_513149/',
 'https://www.pisos.com/comprar/piso-chamartin_ciudad_jardin28002-52568273398_108500/',
 'https://www.pisos.com/alquilar/piso-pinar_del_rey28043-54226020507_100500/',
 'https://www.pisos.com/comprar/piso-centro_palacio28005-52595423612_102100/',
 'https://www.pisos.com/alquilar/piso-ciudad_lineal_san_pascual28027-53390153377_100200/',
 'https://www.pisos.com/comprar/piso-salamanca_castellana28006-32552168529_108900/',
 'https://www.pisos.com/comprar/piso-palomeras_bajas28018-52580891430_100500/',
 'https://www.pisos.com/comprar/piso-palomeras_sureste28018-53354690923_100200/',
 'https://www.pisos.com/alquilar/piso-chopera28045-54199273174_100200/',
 'https://www.pisos.com/alquilar/piso-ciudad_lineal_san_pascual28027-54252937314_108900/',
 'https://www.pisos.com/comprar/piso-retiro_pacifico28007-54265767350_100500/',
 'https://www.pisos.com/alquilar/piso-ciudad_universitaria28035-54242986762_109300/',
 'https://www.pisos.com/alquilar/piso-sol_barrio28013-53427417788_100500/',
 'https://www.pisos.com/alquilar/piso-goya28001-54200563228_108900/',
 'https://www.pisos.com/comprar/estudio-piovera28043-54182667663_109800/',
 'https://www.pisos.com/alquilar/piso-trafalgar28010-54207744004_100500/',
 'https://www.pisos.com/comprar/apartamento-goya28028-54262135015_100500/',
 'https://www.pisos.com/comprar/piso-jeronimos28014-35016200793_100500/',
 'https://www.pisos.com/alquilar/piso-lista_barrio28006-42587546557_100500/',
 'https://www.pisos.com/alquilar/piso-fuente_del_berro28028-54210966519_108900/',
 'https://www.pisos.com/comprar/piso-pilar28029-54212500910_100200/',
 'https://www.pisos.com/comprar/piso-moscardo28026-52566049434_100200/',
 'https://www.pisos.com/comprar/piso-valdezarza28039-53419191960_108500/',
 'https://www.pisos.com/alquilar/piso-salamanca_castellana28006-53425461171_100500/',
 'https://www.pisos.com/alquilar/piso-goya28006-42573675870_100500/',
 'https://www.pisos.com/comprar/piso-tetuan_almenara28020-96714056402_517093/',
 'https://www.pisos.com/alquilar/piso-moncloa_aravaca_arguelles28008-53338969817_109800/',
 'https://www.pisos.com/comprar/piso-carabanchel_vista_alegre28025-54222155749_101800/',
 'https://www.pisos.com/comprar/piso-alameda_de_osuna_barrio-52585131250_105100/',
 'https://www.pisos.com/alquilar/piso-cortes_huertas28012-35854195146_440000/',
 'https://www.pisos.com/alquilar/estudio-justicia_chueca28004-54254362681_104700/',
 'https://www.pisos.com/alquilar/piso-acacias28026-54200247113_102100/',
 'https://www.pisos.com/comprar/piso-ciudad_lineal_quintana-53390404763_108900/',
 'https://www.pisos.com/comprar/piso-san_blas_salvador28027-51714878779_100500/',
 'https://www.pisos.com/comprar/piso-lista_barrio28006-53393563048_529748/',
 'https://www.pisos.com/alquilar/piso-trafalgar28010-54185346736_521737/',
 'https://www.pisos.com/alquilar/piso-tetuan_almenara28029-54169360732_108500/',
 'https://www.pisos.com/alquilar/piso-cortes_huertas28014-53427801518_108900/',
 'https://www.pisos.com/alquilar/piso-san_blas_simancas28037-54231127069_109800/',
 'https://www.pisos.com/comprar/piso-guindalera28002-53427402012_102100/',
 'https://www.pisos.com/comprar/piso-recoletos28001-47508658596_108900/',
 'https://www.pisos.com/alquilar/piso-arganzuela_delicias-54230118536_108900/',
 'https://www.pisos.com/comprar/piso-imperial28005-53399776882_100500/',
 'https://www.pisos.com/alquilar/piso-puente_de_vallecas_san_diego28053-53344007323_100500/',
 'https://www.pisos.com/comprar/piso-puente_de_vallecas_san_diego28053-54222168505_100200/',
 'https://www.pisos.com/comprar/duplex-berruguete28039-52534136637_100200/',
 'https://www.pisos.com/comprar/piso-san_blas_simancas28037-5337014516_109700/',
 'https://www.pisos.com/comprar/piso-palomeras_bajas28018-52501248309_103800/',
 'https://www.pisos.com/comprar/piso-chamberi_arapiles28015-52527321650_101000/',
 'https://www.pisos.com/alquilar/piso-trafalgar28010-42516933738_100500/',
 'https://www.pisos.com/alquilar/piso-justicia_chueca28004-52546728652_100500/',
 'https://www.pisos.com/alquilar/piso-zofio28026-54203535086_104700/',
 'https://www.pisos.com/alquilar/estudio-castillejos28020-54177834965_100500/',
 'https://www.pisos.com/alquilar/piso-moncloa_aravaca_arguelles28008-54171571412_100200/',
 'https://www.pisos.com/comprar/piso-justicia_chueca28001-52575830786_102100/',
 'https://www.pisos.com/comprar/piso-centro_palacio28005-52512483333_102100/',
 'https://www.pisos.com/alquilar/piso-legazpi_barrio28045-54200211918_109800/',
 'https://www.pisos.com/comprar/piso-san_blas_salvador28027-52537208124_108500/',
 'https://www.pisos.com/comprar/piso-ibiza28009-46722428206_102100/',
 'https://www.pisos.com/alquilar/piso-acacias28005-53418168606_100500/',
 'https://www.pisos.com/comprar/piso-ventas28017-46760579550_100200/',
 'https://www.pisos.com/alquilar/piso-recoletos28046-52549383727_100500/',
 'https://www.pisos.com/comprar/piso-ciudad_lineal_quintana-50893554780_100200/',
 'https://www.pisos.com/alquilar/apartamento-chamartin_hispanoamerica28016-52542532287_101800/',
 'https://www.pisos.com/comprar/duplex-costillares28033-54176569615_104700/',
 'https://www.pisos.com/comprar/piso-berruguete28039-54204263054_100200/',
 'https://www.pisos.com/alquilar/piso-ventas28017-54227281078_108900/',
 'https://www.pisos.com/alquilar/piso-lista_barrio28006-53362501580_100500/',
 'https://www.pisos.com/comprar/piso-goya28001-54214850712_100500/',
 'https://www.pisos.com/comprar/piso-pinar_del_rey28043-54251402053_100200/',
 'https://www.pisos.com/comprar/piso-las_aguilas28044-49199270554_518874/',
 'https://www.pisos.com/comprar/apartamento-ciudad_universitaria28040-52542553428_100500/',
 'https://www.pisos.com/comprar/loft-pinar_del_rey28033-53429917829_529625/',
 'https://www.pisos.com/comprar/piso-sol_barrio28013-53432052383_100500/',
 'https://www.pisos.com/alquilar/estudio-berruguete28039-53345099965_104700/',
 'https://www.pisos.com/alquilar/piso-tetuan_almenara28046-54259348203_108900/',
 'https://www.pisos.com/comprar/piso-barrio_de_salamanca_lista28006-52583317752_100500/',
 'https://www.pisos.com/alquilar/apartamento-carabanchel_comillas28019-50078353350_100500/',
 'https://www.pisos.com/alquilar/piso-fuencarral_el_pardo_las_tablas28050-54259539890_106000/',
 'https://www.pisos.com/comprar/piso-villaverde_los_rosales28021-52525918841_515004/',
 'https://www.pisos.com/alquilar/piso-goya28001-54237625448_108900/',
 'https://www.pisos.com/comprar/piso-orcasur28041-5398003115_109700/',
 'https://www.pisos.com/alquilar/piso-puente_de_vallecas_san_diego28018-21711813995_100500/',
 'https://www.pisos.com/comprar/piso-hortaleza_canillas28043-53390515881_106700/',
 'https://www.pisos.com/comprar/piso-ciudad_lineal_san_pascual28027-35009503547_105100/',
 'https://www.pisos.com/comprar/piso-sol_barrio28013-50895699546_100500/',
 'https://www.pisos.com/alquilar/apartamento-universidad_malasana28004-52560073731_101800/',
 'https://www.pisos.com/alquilar/piso-chamartin_el_viso28002-54259512321_100500/',
 'https://www.pisos.com/comprar/piso-chamberi_almagro28010-51673642102_108500/',
 'https://www.pisos.com/comprar/piso-puente_de_vallecas_san_diego28053-54217034477_108500/',
 'https://www.pisos.com/comprar/piso-butarque28021-54196104348_100500/',
 'https://www.pisos.com/comprar/piso-trafalgar28010-53371231652_100500/',
 'https://www.pisos.com/comprar/piso-recoletos28046-53341570823_100500/',
 'https://www.pisos.com/alquilar/piso-villaverde_san_cristobal-54197623633_100500/',
 'https://www.pisos.com/alquilar/piso-pilar28034-54261784178_108900/',
 'https://www.pisos.com/comprar/piso-fuencarral_el_pardo_las_tablas28055-51686406045_108500/',
 'https://www.pisos.com/alquilar/piso-trafalgar28010-42502568361_100500/',
 'https://www.pisos.com/alquilar/apartamento-chamberi_almagro28010-51691363971_101800/',
 'https://www.pisos.com/comprar/piso-chamartin_hispanoamerica28016-52539146539_104700/',
 'https://www.pisos.com/comprar/piso-sol_barrio28013-53394566327_996542/',
 'https://www.pisos.com/comprar/piso-ventas28017-54244110670_100500/',
 'https://www.pisos.com/alquilar/piso-centro_palacio28011-54175752909_102100/',
 'https://www.pisos.com/alquilar/piso-rios_rosas28003-51679213939_108900/',
 'https://www.pisos.com/alquilar/piso-goya28006-54236640240_102100/',
 'https://www.pisos.com/alquilar/piso-pinar_del_rey28033-52579956990_100200/',
 'https://www.pisos.com/comprar/piso-latina_aluche28024-53420573709_100200/',
 'https://www.pisos.com/comprar/piso-recoletos28001-51742144198_108500/',
 'https://www.pisos.com/alquilar/piso-san_blas_rosas28022-54247396586_108900/',
 'https://www.pisos.com/comprar/piso-carabanchel_san_isidro28019-54213468424_518589/',
 'https://www.pisos.com/comprar/piso-chamberi_almagro28010-52586417401_108900/',
 'https://www.pisos.com/comprar/piso-retiro_pacifico28007-48431830973_381300/',
 'https://www.pisos.com/comprar/piso-vinateros-50892646236_106000/',
 'https://www.pisos.com/comprar/piso-chamartin_el_viso28036-52556564451_102100/',
 'https://www.pisos.com/comprar/piso-ciudad_universitaria28040-54208654963_106000/',
 'https://www.pisos.com/comprar/piso-acacias28045-54260682632_102100/',
 'https://www.pisos.com/comprar/piso-puerta_bonita-54245964998_106600/',
 'https://www.pisos.com/comprar/apartamento-trafalgar28010-48373263002_100500/',
 'https://www.pisos.com/alquilar/piso-trafalgar28010-47566833885_100500/',
 'https://www.pisos.com/comprar/piso-valdeacederas28029-50931552331_100200/',
 'https://www.pisos.com/alquilar/piso-lucero28011-54225905975_108900/',
 'https://www.pisos.com/alquilar/piso-piovera28043-52511371793_108900/',
 'https://www.pisos.com/alquilar/apartamento-centro_palacio28005-54264967818_101800/',
 'https://www.pisos.com/comprar/piso-puerta_del_angel-51717597671_100200/',
 'https://www.pisos.com/alquilar/apartamento-retiro_estrella28007-53340710745_101800/',
 'https://www.pisos.com/comprar/piso-ventas28017-54177771697_100500/',
 'https://www.pisos.com/alquilar/piso-imperial28005-52548342025_529055/',
 'https://www.pisos.com/comprar/piso-justicia_chueca28046-44259768406_102100/',
 'https://www.pisos.com/alquilar/piso-puente_de_vallecas_san_diego28053-53424726024_100500/',
 'https://www.pisos.com/alquilar/piso-nueva_espana28036-53406146785_100500/',
 'https://www.pisos.com/comprar/apartamento-hortaleza_canillas28043-51697487470_100500/',
 'https://www.pisos.com/alquilar/piso-chamberi_almagro-54168611758_106600/',
 'https://www.pisos.com/comprar/piso-lista_barrio28006-53423670044_108900/',
 'https://www.pisos.com/comprar/piso-recoletos28001-54195667468_100500/',
 'https://www.pisos.com/alquilar/piso-chamartin_hispanoamerica28016-49191656125_996542/',
 'https://www.pisos.com/comprar/piso-casco_historico_de_vallecas28031-53404011219_100500/',
 'https://www.pisos.com/comprar/piso-montecarmelo28049-53400999411_100200/',
 'https://www.pisos.com/alquilar/piso-penagrande28035-54202533932_108900/',
 'https://www.pisos.com/alquilar/piso-rio_rosas28003-54256508648_516598/',
 'https://www.pisos.com/comprar/piso-carabanchel_buenavista28044-54235597549_105700/',
 'https://www.pisos.com/alquilar/piso-guindalera28028-53364524489_108900/',
 'https://www.pisos.com/alquilar/piso-universidad_malasana28013-44183175419_100500/',
 'https://www.pisos.com/alquilar/piso-pinar_del_rey28033-54202741255_108900/',
 'https://www.pisos.com/comprar/piso-numancia28038-54210819013_100500/',
 'https://www.pisos.com/alquilar/piso-cortes_huertas28014-54213010822_100500/',
 'https://www.pisos.com/comprar/estudio-chopera28045-54234403111_106700/',
 'https://www.pisos.com/comprar/piso-moncloa_aravaca_arguelles28008-51725612073_100200/',
 'https://www.pisos.com/alquilar/apartamento-chamberi_vallehermoso28003-54234313638_101800/',
 'https://www.pisos.com/alquilar/piso-castilla28034-54228984494_102100/',
 'https://www.pisos.com/alquilar/piso-lista_barrio28006-54261368740_108500/',
 'https://www.pisos.com/alquilar/piso-tetuan_cuatro_caminos28020-54252696547_100500/',
 'https://www.pisos.com/comprar/piso-recoletos28001-37541355595_100500/',
 'https://www.pisos.com/comprar/piso-ibiza28009-52597261811_108500/',
 'https://www.pisos.com/alquilar/piso-universidad_malasana28004-54171826819_100500/',
 'https://www.pisos.com/alquilar/piso-ibiza28009-42532634191_100500/',
 'https://www.pisos.com/comprar/piso-ventas28017-52588716110_100200/',

In [38]:
f"{len(to_insert)} URLs nuevas  •  {len(to_update)} a actualizar  •  {len(to_remove)} a marcar como removed"

'1869 URLs nuevas  •  3425 a actualizar  •  1731 a marcar como removed'

#### Insertar o actualizar recorriendo el df

In [42]:
# funcion auxiliar que inserta valores si no existen 
# y devuelve el id creado o ya existente
def get_or_create(table, keycol, keyval, idcol, extras=None):
    # intenta SELECT
    sql = f"SELECT {idcol} FROM {table} WHERE {keycol}=%s"
    cursor.execute(sql, (keyval,))
    r = cursor.fetchone()
    if r:
        return r[0]
    # si no existe, INSERT
    cols = [keycol] + (list(extras.keys()) if extras else [])
    vals = [keyval] + (list(extras.values()) if extras else [])
    ph = ",".join(["%s"]*len(vals))
    sql = f"INSERT INTO {table} ({','.join(cols)}) VALUES ({ph})"
    cursor.execute(sql, vals)
    return cursor.lastrowid

In [40]:
bool_feats = [
    'ascensor','balcon','calefaccion','chimenea','cocina_equipada','exterior',
    'garaje','jardin','piscina','trastero','terraza','adaptado_movilidad_reducida',
    'aire_acondicionado','puerta_blindada','vidrios_dobles','sistema_seguridad'
]

In [44]:
df_all = df_all.replace({np.nan:None})

In [ ]:
for idx, row in df_all.iterrows():
    url = row['url']
    
    # 7.1 LOCATION
    loc_id = get_or_create(
        'location','barrio', row['barrio'], 'location_id',
        extras={'distrito': row['distrito']}
    )
    
    # 7.2 AGE_RANGE
    age_id = None
    if pd.notna(row['antiguedad']):
        age_id = get_or_create('age_range','label', row['antiguedad'], 'age_range_id')
    
    # 7.3 PROPERTY (upsert via ON DUPLICATE KEY)
    pk_native = row['property_id']
    prop_cols = [
        'location_id','latitude','longitude','property_native_id',
        'superficie_construida','superficie_util','habitaciones','banos',
        'planta','estado_conservacion','age_range_id'
    ]
    prop_vals = [
        loc_id, row['latitude'], row['longitude'], pk_native,
        row['superficie_construida'], row['superficie_util'],
        row['habitaciones'], row['banos'], row['planta_numerica'],
        row['conservacion'], age_id
    ]
    upd = ",".join(f"{c}=VALUES({c})" for c in prop_cols[1:])
    sql_prop = (
        f"INSERT INTO property ({','.join(prop_cols)}) "
        f"VALUES ({','.join(['%s']*len(prop_vals))}) "
        f"ON DUPLICATE KEY UPDATE {upd}"
    )
    cursor.execute(sql_prop, prop_vals)
    # recuperar el property_id real
    if pk_native in map_prop:
        property_id = map_prop[pk_native]
    else:
        property_id = cursor.lastrowid
        map_prop[pk_native] = property_id

    # 7.4 ENERGY_CERTIFICATE
    if pd.notna(row['energy_consumption_kwh_m2_yr']) or pd.notna(row['energy_emissions_kg_co2_m2_yr']):
        sql_ec = """
        INSERT INTO energy_certificate
          (property_id,classification,consumo_rating,emisiones_rating,emision_value,consumption_value)
        VALUES (%s,%s,%s,%s,%s,%s)
        ON DUPLICATE KEY UPDATE
          classification=VALUES(classification),
          consumo_rating=VALUES(consumo_rating),
          emisiones_rating=VALUES(emisiones_rating),
          emision_value=VALUES(emision_value),
          consumption_value=VALUES(consumption_value)
        """
        cursor.execute(sql_ec, (
            property_id,
            row['energy_cert_classification'],
            row['energy_consumption_rating'],
            row['energy_emissions_rating'],
            row['energy_emissions_kg_co2_m2_yr'],
            row['energy_consumption_kwh_m2_yr'],
        ))

    # 7.5 FEATURES EAV
    for feat in bool_feats:
        if row.get(feat) is True:
            # obtener o crear feature_id
            if feat not in feat_map:
                fid = get_or_create('feature_catalog','nombre',feat,'feature_id')
                feat_map[feat] = fid
            else:
                fid = feat_map[feat]
            # insertar en property_feature
            cursor.execute(
                "INSERT IGNORE INTO property_feature(property_id,feature_id) VALUES(%s,%s)",
                (property_id, fid)
            )

    # 7.6 LISTING INSERT / UPDATE
    price = row['price_eur']
    scraped_at = row['scraped_at']
    desc = row['description']
    if url in map_list:
        # UPDATE
        lid = map_list[url]
        cursor.execute("""
            UPDATE listing
               SET price_eur=%s, scraped_at=%s, scrape_status=%s, description=%s
             WHERE listing_id=%s
        """, (price, scraped_at, 'Success', desc, lid))
    else:
        # INSERT
        sql_l = """
        INSERT INTO listing
          (property_id,url,listing_type,price_kind,price_eur,scraped_at,scrape_status,description)
        VALUES (%s,%s,%s,%s,%s,%s,%s,%s)
        """
        cursor.execute(sql_l, (
            property_id, url, row['listing_type'], row['price_kind'],
            price, scraped_at, 'Success', desc
        ))
        map_list[url] = cursor.lastrowid

    # Commit cada 200 filas
    if idx % 200 == 0:
        conn.commit()

# commit final
conn.commit()
print("Insert/Update completado.")

In [ ]:
if to_remove:
    params = tuple(to_remove)
    sql = f"UPDATE listing SET scrape_status='Removed' WHERE url IN ({','.join(['%s']*len(params))})"
    cursor.execute(sql, params)
    conn.commit()
    print(f"{len(params)} anuncios marcados como Removed.")
else:
    print("No hay anuncios para marcar como Removed.")

In [ ]:
cursor.close()
conn.close()

Creamos tres df, los anuncios nuevos (a insertar), los anuncios existentes (a actualizar), y los que ya no existen (marcar como borrados-remove)

In [46]:
urls_nuevas   = set(df_all['url']) - set(map_list.keys())
urls_existentes = set(df_all['url']) & set(map_list.keys())
urls_remover = set(map_list.keys()) - set(df_all['url'])

print(f"{len(urls_nuevas)} nuevas, {len(urls_existentes)} existentes, {len(urls_remover)} a marcar removed")

1866 nuevas, 3428 existentes, 1731 a marcar removed

In [47]:
df_insert = df_all[df_all['url'].isin(urls_nuevas)].copy()
df_insert

,property_id,url,listing_type,price_kind,price_eur,scraped_at,description,barrio,distrito,latitude,...,jardin,piscina,trastero,terraza,adaptado_movilidad_reducida,aire_acondicionado,puerta_blindada,vidrios_dobles,sistema_seguridad,acepta_mascotas
7,5.503627e+10,https://www.pisos.com/alquilar/piso-palos_de_m...,rental,rent_month,1800.0,2025-06-16T17:52:13.878117,**************** DISPONIBILIDAD INMEDIATA EN A...,Palos de Moguer,Arganzuela,40.40554,...,False,False,False,False,False,False,False,False,False,False
8,5.501051e+10,https://www.pisos.com/alquilar/piso-chamartin_...,rental,rent_month,1700.0,2025-06-16T17:52:15.796883,"Descubre esta funcional vivienda en alquiler, ...",Ciudad Jardín,Chamartín,40.448575,...,False,False,False,False,True,True,False,True,False,None
12,4.921083e+10,https://www.pisos.com/alquilar/piso-guindalera...,rental,rent_month,1000.0,2025-06-16T17:52:23.305206,Tecnocasa Estudio Guindalera valquila estudio ...,Guindalera,Salamanca,40.43531,...,False,False,False,False,False,True,False,False,False,None
18,5.500720e+10,https://www.pisos.com/alquilar/atico-moncloa_a...,rental,rent_month,3600.0,2025-06-16T17:52:34.979723,En Remax People NO cobramos comisión a los inq...,Aravaca,Moncloa-Aravaca,40.458953,...,True,True,True,True,False,True,False,False,False,None
22,4.251388e+10,https://www.pisos.com/alquilar/atico-trafalgar...,rental,rent_month,3165.0,2025-06-16T17:52:43.054925,*APARTAMENTO CON TERRAZA* *COMPLETAMENTE AMUEB...,Trafalgar,Chamberí,40.431246,...,False,False,False,True,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5288,5.504378e+10,https://www.pisos.com/comprar/piso-san_blas_ca...,sale,sale_price,240000.0,2025-06-16T20:41:51.151323,INMOBILIARIA REDPISO CANILLEJAS pone en venta ...,Canillejas,San Blas,40.439323,...,False,False,False,False,False,True,True,False,False,None
5290,5.084455e+10,https://www.pisos.com/comprar/piso-goya28009-5...,sale,sale_price,1300000.0,2025-06-16T20:41:54.731735,*Las imágenes de las estancias amuebladas y de...,Goya,Salamanca,40.424744,...,False,False,False,False,False,False,True,False,False,None
5291,4.756165e+10,https://www.pisos.com/comprar/apartamento-goya...,sale,sale_price,1800000.0,2025-06-16T20:41:56.595975,"Engel & Völkers, inmobiliaria de lujo, tiene e...",Goya,Salamanca,40.421674,...,False,False,False,False,False,False,False,False,False,None
5292,4.587160e+10,https://www.pisos.com/comprar/atico-universida...,sale,sale_price,1080000.0,2025-06-16T20:41:58.381915,Fortuny Real Estate ofrece ático de lujo a est...,Universidad-Malasaña,Centro,40.425055,...,False,True,False,True,False,False,False,False,False,None
5293,5.418658e+10,https://www.pisos.com/comprar/apartamento-reco...,sale,sale_price,2309000.0,2025-06-16T20:42:00.278871,Engel & Völkers tiene el placer de presentar e...,Recoletos,Salamanca,40.425238,...,False,False,False,False,False,False,False,False,False,None

In [48]:
df_update = df_all[df_all['url'].isin(urls_existentes)].copy()
df_update

,property_id,url,listing_type,price_kind,price_eur,scraped_at,description,barrio,distrito,latitude,...,jardin,piscina,trastero,terraza,adaptado_movilidad_reducida,aire_acondicionado,puerta_blindada,vidrios_dobles,sistema_seguridad,acepta_mascotas
0,5.507919e+10,https://www.pisos.com/alquilar/piso-penagrande...,rental,rent_month,1500.0,2025-06-16T17:51:59.469159,31Real Servicios Inmobiliarios alquila moderno...,Peñagrande,Fuencarral-El Pardo,40.47559,...,True,True,False,True,False,True,False,False,False,None
1,5.500978e+10,https://www.pisos.com/alquilar/piso-penagrande...,rental,rent_month,1800.0,2025-06-16T17:52:02.329418,31Real Servicios Inmobiliarios presenta este e...,Peñagrande,Fuencarral-El Pardo,40.4725,...,True,False,False,True,False,True,False,False,False,None
2,5.509968e+10,https://www.pisos.com/alquilar/piso-penagrande...,rental,rent_month,1600.0,2025-06-16T17:52:04.222347,31real servicios inmobiliarios alquila viviend...,Peñagrande,Fuencarral-El Pardo,40.4733,...,False,False,True,False,False,True,False,False,False,None
3,5.342772e+10,https://www.pisos.com/alquilar/piso-recoletos2...,rental,rent_month,7750.0,2025-06-16T17:52:06.371839,222m / 4 dormitorios / 4 Baños / Trastero / Po...,Recoletos,Salamanca,40.4223,...,False,False,True,False,False,True,True,False,False,None
4,5.253707e+10,https://www.pisos.com/alquilar/piso-chamberi_a...,rental,rent_month,1000.0,2025-06-16T17:52:08.229176,ALQUILER TEMPORAL DISPONIBLE DESDE EL 01 DE JU...,Arapiles,Chamberí,40.43619,...,False,False,False,False,False,True,False,False,False,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5279,5.420586e+10,https://www.pisos.com/comprar/piso-chamberi_ar...,sale,sale_price,840000.0,2025-06-16T20:41:34.477114,Piso reformado con encanto en pleno Chamberí –...,Arapiles,Chamberí,40.414908,...,False,False,False,False,False,True,False,False,True,None
5281,5.308727e+09,https://www.pisos.com/comprar/piso-san_blas_si...,sale,sale_price,324091.0,2025-06-16T20:41:38.005521,VT5. P1 3ºH. Piso en una finca de obra nueva d...,Simancas,San Blas,40.434124,...,False,False,True,True,False,False,False,False,False,None
5282,5.173728e+10,https://www.pisos.com/comprar/piso-ibiza28009-...,sale,sale_price,645000.0,2025-06-16T20:41:39.847382,Encantador piso en el prestigioso barrio de Ib...,Ibiza,Retiro,40.419641,...,False,False,False,False,True,True,False,False,False,None
5284,5.166989e+10,https://www.pisos.com/comprar/piso-villa_de_va...,sale,sale_price,289490.0,2025-06-16T20:41:43.440166,"Acogedor y luminoso piso en Santa Eugenia, Vil...",Santa Eugenia,Villa de Vallecas,40.37905,...,False,False,False,True,True,True,False,False,False,None
5289,5.339863e+10,https://www.pisos.com/comprar/piso-pilar28029-...,sale,sale_price,290000.0,2025-06-16T20:41:52.935318,Nmobiliaria tecnocasa barrio del pilar-la vagu...,Pilar,Fuencarral-El Pardo,40.478543,...,False,False,False,True,False,False,False,False,False,None

In [49]:
df_remove = (pd.DataFrame({'url': list(urls_remover)})
               .assign(listing_id=lambda d: d['url'].map(map_list))
            )
df_remove

                                                    url  listing_id
0     https://www.pisos.com/comprar/piso-centro_pala...        3213
1     https://www.pisos.com/alquilar/piso-pinar_del_...        1527
2     https://www.pisos.com/comprar/piso-palomeras_b...        4341
3     https://www.pisos.com/comprar/piso-ventas28017...        4824
4     https://www.pisos.com/comprar/piso-villaverde_...        3683
...                                                 ...         ...
1726  https://www.pisos.com/comprar/piso-san_blas_ca...        3535
1727  https://www.pisos.com/comprar/apartamento-univ...        4935
1728  https://www.pisos.com/comprar/piso-puente_de_v...        2837
1729  https://www.pisos.com/alquilar/piso-guindalera...        1168
1730  https://www.pisos.com/alquilar/piso-piovera280...         109

[1731 rows x 2 columns]

Marcamos los anuncios borrados como "removed"

In [50]:
if not df_remove.empty:
    ids = df_remove['listing_id'].tolist()
    sql = f"UPDATE listing SET scrape_status='Removed' WHERE listing_id IN ({','.join(['%s']*len(ids))})"
    cursor.execute(sql, ids)
    conn.commit()
    print(f"Marcados {len(ids)} listings como Removed")

Marcados 1731 listings como Removed